### ISSUE TITLE
Credits screen

### ISSUE THREAD

**Issue by clintbellanger** [flareteam/flare-engine#116]
I figure the easiest way to do this to have a movie style credits scroll, with the text read from a config file.

Maybe an optional background image and background music.

This sounds like a new Game State. Maybe put a Credits button on one of the bottom corners of the Title screen.

**Comment by dorkster** [comment]
Cutscenes support the aforementioned "movie-style" scrolling now! See: https://github.com/clintbellanger/flare-engine/commit/6aca805b54e3234202f3fd1244b511d262e44a32

Preview:
![output](https://cloud.githubusercontent.com/assets/913982/16711234/b8de196c-461e-11e6-8eee-c0153fc1856d.gif)

**Comment by clintbellanger** [comment]
Nice! I like how simple the config file is. For some reason I was making this feature way too complex in my head.

**Comment by Jeffry84** [comment]
Honestly much better for me as well. Nice and simple :)
