### ISSUE TITLE
Crash on Windows XP at game start (CPU without SSE)

### ISSUE THREAD

**Issue by igorko** [flareteam/flare-engine#1396]
Our sdl_12 branch now is up-to-date with master and can be built using both SDL1.2 and SDL2 versions (as in old good times). I have made this to test crash, reported by one of our users(Rem). (On his Windows XP SDL2 version is crashing at start, for me it worked.) As a result updated SDL1.2 version crashes for me on Windows XP (but works on Windows 7). Crash happens after reporting that no joysticks were found. Can anyone look into it?

**Comment by igorko** [comment]
Compiler used: MSVC 2012.

**Comment by igorko** [comment]
GCC build (provided by @dorkster ) works for me on WIndows7 and Windows XP (VM), and still crashes for Rem on real Windows XP.

**Comment by dorkster** [comment]
If Rem hasn't already, he might have to set `hwsurface=0` and `vsync=0` in settings.txt. I have to do this in my Windows 7 VM.

**Comment by igorko** [comment]
I have removed DOUBLEBUF from sdl_12 (it was undefined!) and for me it works now.

**Comment by dorkster** [comment]
You could probably set DOUBLEBUF to the value of VSYNC, since those were one in the same for our old builds.

**Comment by igorko** [comment]
I just used VSYNC for setting up sdl1.2 context.

**Comment by igorko** [comment]
Still doesn't work for Rem. His PC configuration:

winxp 2002 sp3
amd athlon 1.10GHz
1Go RAM
Nvidia GeForce FX 5500

**Comment by igorko** [comment]
@dorkster said:
> If Rem hasn't already, he might have to set hwsurface=0 and vsync=0 in          %APPDATA\flare\config\settings.txt. I have to do this in my Windows 7 VM. The crash happens in         SDL I believe, so our fallbacks in createContext() won't work

@dorkster Can we set hwsurface=0 and vsync=0 if context creation failed and try again? For me createContext() can fail in VM (3D acceleration disabled) and app exits normally. In this case trying to create context once again will help. (write log to message that hwsurfaces and vsync were disabled). Btw, disabling these two settings helps to start in both sw and hw modes of sdl2.

**Comment by dorkster** [comment]
>Can we set hwsurface=0 and vsync=0 if context creation failed and try again?

We try to do exactly that here: https://github.com/clintbellanger/flare-engine/blob/master/src/SDLSoftwareRenderDevice.cpp#L281

**Comment by igorko** [comment]
I guess that logic is somehow broken, because if both setting are enabled when 3d is disabled in vm, game exits correctly with createContext failed error. If both are disabled, context is created... can you check it under windows xp vm, 3d disabled?

**Comment by dorkster** [comment]
In my VM, it just crashes in SDL_CreateRenderer(), so it's completely unable to reach the fallback code.

Fortunately, I figured out why your game is exiting instead of hitting the fallback functionality. I'll put together a fix for that.

**Comment by igorko** [comment]
I have asked Rem to try some debug builds, and some crash without executing any lines of code from main. And as you see from screenshot, in some cases part of code is executed. Is's a question, when it crashes - at start or ar context creating. But one thing is known - 0.19 build from flarerpg site works well, while both SDL2 and SDL1.2 builds from master crash. This is a Question, WHY. Issue can be related to compiler, which was used for both SDL and flare, but I hope it's not.

**Comment by igorko** [comment]
I have noticed that msvc build was crashing one time, but after rebuild it worked well inside windows xp vm (while both worked well on host). For Rem, my msvc builds were crashing right at start. But gcc build ( @dorkster , your build) executed some lines before crash. I have next idea: @dorkster can you provide another gcc build with some logging so we know where exactly it crashes. Also maybe SDL has some more functions which allow to check if system is supported (driver etc). Having this in log would be nice. And if log will not help,  is it possible to get some stacktrace using gdb from debug build on user machine without any dev environment. If so, having instructions would be nice(I'm not familiar with using gdb from console...)

**Comment by igorko** [comment]
http://gamedev.stackexchange.com/questions/81917/how-to-detect-graphics-api-at-runtime-with-sdl2

**Comment by dorkster** [comment]
I created a new build with MinGW that has some extra logging information: https://drive.google.com/file/d/0B1BVtHygCIkWdGxob0RUd0FwUXM/view?usp=sharing

Testing in my Win7 vm, the **video** driver was always "windows" and the **render** driver reported the same drivers and flags as my main Linux system. So I don't see any way we can automatically detect driver support, at least through SDL.

**Comment by dorkster** [comment]
Looking at Rem's hardware, I'm starting to think there might be something having to do with his CPU. There are some 1.1Ghz Athlon processors that don't have support for things like SSE. It might be possible that some of the past builds have used SSE and other things for optimization. Running an SSE optimized binary on a system that doesn't support it would cause a crash, right?

I'm pretty sure the latest build I linked was built with CMAKE_RELEASE_TYPE=Debug this time around. I say "pretty sure" since I'm not used to Code::Blocks, or development on Windows in general. Anyway, when Debug is on, we compile with optimization level -O0, so that should turn off any fancy stuff.

**Comment by igorko** [comment]
Interesting idea, maybe 0.19 was built without any optimizations (includind SDL build) Here some tris aere done https://code.google.com/p/keeperfx/issues/detail?id=576.  That might be a reason why current msvc build using SDL1.2 doesn't work(0.19 was using gcc SDL build). @clintbellanger what SDL1.2 package was you using when building 0.19 wor Windows? Archives from SDL site? Or custom build?

**Comment by igorko** [comment]
@dorkster may I ask you for another build? (I don't have internet on my pc, nor mingw installed)Can you get SDL1.2 development packages from SDL site
https://www.libsdl.org/download-1.2.php
https://www.libsdl.org/projects/SDL_mixer/release-1.2.html
https://www.libsdl.org/projects/SDL_image/release-1.2.html
https://www.libsdl.org/projects/SDL_ttf/release-1.2.html

merge latest changes from master into sdl12 branch and build sdl12 version of flare?

**Comment by dorkster** [comment]
Here's an SDL 1.2 build: https://drive.google.com/file/d/0B1BVtHygCIkWRmVZbGg0QU44eU0/view?usp=sharing

**Comment by igorko** [comment]
Looking here, http://en.m.wikipedia.org/wiki/List_of_AMD_Athlon_XP_microprocessors, there was no athlon xp with 1.1GHz frequency, maybe Rem's pc has defaulted bios, so frequency is not optimal. But anyway looking in above table, all athlons xp have the same instructions set, and on my Barton model all works fine... (I don't take mobile and server version into account)

**Comment by dorkster** [comment]
@igorko I was looking [here](http://www.cpu-world.com/CPUs/K7/AMD-Athlon%201100%20-%20A1100AMT3B.html) when I made that hypothesis. Good point though that it could be a different CPU being frequency scaled.

**Comment by igorko** [comment]
I thought it was ahlon xp, now I see it's just athlon, my mistake. http://en.m.wikipedia.org/wiki/List_of_AMD_Athlon_microprocessors So cpu frequency can be correct

**Comment by igorko** [comment]
Searching the way to disable sse in vm for testing sdl libs, as Rem doesn't respond recently. We should add some sort of troubleshooting to flare readme about e.g. SSE  and disabling vsync/hwsurface

**Comment by igorko** [comment]
https://communities.vmware.com/message/2421290

**Comment by igorko** [comment]
https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport

**Comment by igorko** [comment]
@dorkster are you using virtualbox for virtualization? Can you try last link with 0.19 build and master? (maybe it will require win xp because win7 can fail to start) I should try this too soon (maybe tomorrow)

**Comment by igorko** [comment]
https://msdn.microsoft.com/en-us/library/vstudio/7t5yh4fd(v=vs.110).aspx

**Comment by igorko** [comment]
http://tty.org.ru/node/182 how to setup virtualbox vm with disabled sse. It's in Russian, but Google translate can handle that.

**Comment by igorko** [comment]
http://stackoverflow.com/questions/22446008/winapifamily-h-no-such-file-or-directory-when-compiling-sdl-in-codeblocks

**Comment by igorko** [comment]
I got some results that will allow to close this issue, when Rem will test it on real hardware

First of all how to setup testing environment:

1. get virtualbox 4.2 ( 4.3 did not work for me on Windows host)
2. create windows xp x32 vm.
3. go to virtualbox folder and run
    
		vboxmanage modifyvm vm_name --cpuidset 0x1 0x0001067a 0x00000800 0x00000209 0x018bf3ff
		
this will disable SSE and SSE2 on guest OS. To revert changes execute
		
		vboxmanage modifyvm <name> --cpuidremoveall
		
First command will add next lines to vm_name.vbox file to CPUsection


        <CpuIdTree>
          <CpuIdLeaf id="1" eax="67194" ebx="2048" ecx="521" edx="25949183"/>
        </CpuIdTree>
		
		
second command will remove changes.


Now it's time for testing results.
I have tested official VC and mingw32 development packages from sdl site both SDL1.2 and SDL2 versions.
Note that for SDL1.2 there are not mixer, image and ttf packages, but VC versions of them will work with mingw32 version of SDL 1.2 development package correctly.

Here is test table, empty cell means not tested.

                     |  win xp SSE/SSE2  |  win xp without SSE/SSE2  |  win 7 SSE/SSE2  |
    _____________________________________________________________________________________
    VC SDL1.2        |       +                        -                      +
    _____________________________________|___________________________|__________________|
    mingw32  SDL1.2  |       +                        +                      +
    _____________________________________|___________________________|__________________|
    
    VC SDL2          |       +                        -                      +
    _____________________________________|___________________________|__________________|
    mingw32  SDL2    |       +/-                      -                      +
    _____________________________________|___________________________|__________________|
    
    
    +/-    need to disable vsync/hwsurface to run (otherwise it will crash). If flare is started from cmd,
    exiting the game doesn't return 0 exit code to cmd ( no control is returned to user in cmd)

My conclusion:
1. all VC builds of SDL require SSE to run. We should avoid using VC builds for release.
2. SDL2 mingw build requires SSE to run. We should test mingw builds before release.
3. mingw build of SDL2 has issues with running under xp, @dorkster , you also was having crash in win7 vm. Can you check if exiting flare returns control to cmd?

**Comment by igorko** [comment]
Here is tested build using SDL1.2 mingw32 https://www.dropbox.com/s/8rjkh9vea9b540y/flare-sdl12-mingw-noSSE-official-SDL-libs.zip?dl=0 . I guess @dorkster's sdl1.2 mingw build will works everywhere too, if it was built using the same development libraries.

**Comment by dorkster** [comment]
I tested my minGW builds on 32-bit Windows XP VM with SSE disabled. Results were the same as my testing on Windows 7:

- SDL 1.2 build ran without issue and returned 0 on exit
- SDL 2 build required manually turning off hwsurface and vsync to prevent a crash. Otherwise, it returned 0.

**Comment by igorko** [comment]
Anyway, if it exits correctly (for me it doesn't return control to cmd, but process disappears from processlist and no crash mesage appears) , there is issue with running SDL2 version on some systems with hwsurface and vsync enabled. We should report it to SDL bugtracker, if not yet reported. And for me it doesn't makes difference if it's sw or hw renderer - it crashes anyway. SDL1.2 works ok in the same situation.

**Comment by igorko** [comment]
@dorkster can you try if it crashes on hg version of SDL2? Building sdl for windows can be a challenge, but we will know if issue is fixed. And I'll search in bugzilla.

**Comment by igorko** [comment]
Hm, I wasn't correct when saying that if sdl1.2 works, then sdl2 should too. After looking into our src code I have realized that we use textures even in software renderer, so even our software renderer now depends on videocard (drivers? ). That means that after dropping sdl1.2 we have removed "pure" software rendering. Am I right?

**Comment by dorkster** [comment]
>That means that after dropping sdl1.2 we have removed "pure" software rendering. Am I right?

Yes. The migration guide for SDL 2 said that the best way to go from SDL 1.2 rendering to the new method was to render as normal to an SDL_Surface. Then that SDL_Surface is converted to an SDL_Texture that is displayed on the SDL_Renderer. In our "hardware" renderer, the SDL_Surfaces are omitted from the process.

**Comment by dorkster** [comment]
I just tested a Release build with SDL 2 on the 32-bit XP VM. No crash with hwsurface/vsync off.

I should reiterate that both my Windows VMs didn't have 3d acceleration on. If I enable 3d acceleration in the VM's settings, I get no crashes period. Looking at [this thread](https://forums.libsdl.org/viewtopic.php?p=43003&sid=a10d5129a807d965f41f7abb1bc4f10c), I doubt anything has changed on the SDL side of things.

Still, none of this explains Rem's crash.

**Comment by igorko** [comment]
I guess Rem's cpu lacks sse, so sdl2 doesn't work for him as official sdl2 builds require sse. Sdl1.2 should work for him, so let's wait for responce.

**Comment by igorko** [comment]
You can see from my test table, that all - mean crash.

**Comment by dorkster** [comment]
But that doesn't make sense to me, as I didn't get a crash with SDL 2 on a 32-bit Windows XP VM with SSE disabled.

**Comment by igorko** [comment]
Have you built sdl2 by yourself?

**Comment by dorkster** [comment]
No, I am using the official build of SDL 2 and the extensions.

**Comment by igorko** [comment]
Have you checked that sse is really disabled by cpu-z app?

**Comment by igorko** [comment]
I have removed xp without SSE/SSE2 for VC from test table. Dunno why but I get "app is wrong configured, reinstall app" on one xp vm for both SSE/no SSE cases, while on different VM (with SSE) all works. So there is something with VM, not executable, and I can't test correctly VC without SSE.

**Comment by igorko** [comment]
This can help for testing
http://superuser.com/questions/625648/virtualbox-how-to-force-a-specific-cpu-to-the-guest

http://en.wikipedia.org/wiki/CPUID

**Comment by igorko** [comment]
When usong above cpuid settings, cpu-z still reports sse, so this will not work.

I could upload my vbox vm to dropbox (settings and hdd) , so you could try on both vm's.

**Comment by igorko** [comment]
Building SDL2 from sources (2.0.4) using mingw and next commands:

    ./configure --disable-sse
    make

resolved this issue for me. Official extensions (image, mixer, ttf) were used, they don't have SSE build switches, so work ok.

We should add note to build instructions that SDL2 default build enables SSE support (if you will run just ./configure without flags, you will that SSE is enabled in configure output info). No idea about VC build though.

**Comment by igorko** [comment]
Let's wait for original reporter response and then close this.

**Comment by igorko** [comment]
Also we need to add throubleshooting info that if user gets crash on start, he should try to disable hwsurface and vsync in settings file.

**Comment by dorkster** [comment]
I've added a [troubleshooting section](https://github.com/clintbellanger/flare-engine/blob/master/INSTALL.engine.md#troubleshooting) to the INSTALL.engine.md file. I've also updated the paths of config/userdata files in README.engine.md.

So if I understand all this correctly, only SDL2.dll is causing the issue? If so, we could provide a copy of that with SSE disabled that people could just copy over the default SDL2.dll. I highly doubt people with computers old enough to not have SSE support want to be re-compiling software.

**Comment by igorko** [comment]
You are right. We only get issue with SDL2 (if take in account only mingw32 builds, official VC builds are still unknown). We could provide one non-SSE and SSE build for release, or just first one.

**Comment by igorko** [comment]
See here https://wiki.libsdl.org/Installation#Windows_XP.2FVista.2F7

    As of SDL 2.0.3, the codebase still compiles on Cygwin and MingW32, but we expect these to stop working in the future. 

I don't like this at all. I hope cmake will be able to generate mingw makefiles...

**Comment by dorkster** [comment]
@igorko That doesn't seem like a big deal after reading the following line:

>MingW64 is still supported (and despite the name, can also build 32-bit binaries)

**Comment by dorkster** [comment]
Considering that even CPUs with SSE4 are about a decade old, I'm leaning towards not doing anything about this. I would rather use the official builds of SDL2 instead of having to build and supply our own. I'm removing this from the Pre-1.0 milestone.
