### ISSUE TITLE
Guitar controller support for Bard class

### ISSUE THREAD

**Issue by clintbellanger** [flareteam/flare-engine#1409]
Just a fun idea, in case anyone wants to try. I'd like a Bard class that activates powers by playing button combinations (similar to the short melodies on Ocarina of Time). Then mapping that to Guitar Hero / Rock Band controller inputs.

**Comment by clintbellanger** [comment]
This is mostly a joke request. But if it were implemented, I have a few design thoughts.

First one, how would a player using a guitar do directional movement? Would they need to play with an extra device (keyboard or mouse or controller)?

I don't know if SDL2 supports guitar inputs, but someone can find that out. We could map some of the buttons to existing inputs (e.g. Action/Accept, Cancel) and the notes buttons to new abstract keys.

Before implementing the guitar inputs, I would try adding a "button combo" type of power activation. This can use similar logic to special move inputs for fighting games. 

Imagine we start with a keyboard based combo class that uses the keys "QWERT" as special combo inputs. (These would later be mapped to the 5 guitar notes). If you have an Instrument equipped, pressing these keys can play a tone (e.g. wav file of a string pluck). The 5 keys should represent a common scale in a specific key. Each instrument that is recorded separately could be in a different key, which would add some serious mood to each instrument.

Playing a melody of 4-8 notes (simply pressing those keys in that order) is required to activate a power. This can be done anytime an Instrument is equipped and the other costs are paid (e.g. MP cost).

Example bard powers. I'm trying to use auto-targeting powers to ease control issues.

* Sleepy tune that makes targets non-hostile
* Auto-target lightning strike from above on a thunderous solo
* Split the earth with a heavy bass riff, stunning enemies
* Temporary combat bonuses with an uplifting chorus
* After combat, play a victory fanfare for healing over time

If all the bard powers are cleverly designed, and all use the same key, we can balance the powers so that using them feels like playing a song. There should be an incentive to e.g. to use a mix of powers during combat so that it feels like playing verses and choruses. The healing power used after combat ends can be a fanfare.

**Comment by AustinHaugerud** [comment]
> "I don't know if SDL2 supports guitar inputs"

SDL should be able to using Joystick, it's a matter of which guitar I'd imagine. The kind of guitar one would commonly have (a console guitar) to me looks possible but would be a bit troublesome. If someone wanted to use a wireless Guitar Hero guitar for example, they'd have to buy a wireless adapter. Assuming the user actually has the guitar properly set up however, SDL should be able to interact with it. It'd take some testing to figure out how to map the guitar's controls obviously but I can't see why it wouldn't be possible. 

Other toy guitars with fret buttons could actually be used I think, but then Flare would have to worry about the hardware differences in that guitar, if it has some weird issue like it can't handle multiple button presses at once, plus players are less likely to use these I think. It'd be cool if you could more or less just use any electronic toy guitar, but based on immediate research it doesn't seem feasible to me.

**Comment by dorkster** [comment]
I'm trying to clean up the Issues page a bit right now. As... _unique_... as this idea is, I think it's time to close this one :)

Interestingly, Steam Input has become a thing since this was posted. It supports defining input "chords" that map to the inputs of a typical Xbox 360 controller. Since I'm working on moving to the SDL_GameController API, it would in theory be possible to use Steam Input or something similar to create such mappings.
