### ISSUE TITLE
Translation of "%s Resistance"

### ISSUE THREAD

**Issue by gunchleoc** [flareteam/flare-engine#1472]
I have difficulty translating the following string:

```
%s Resistance
../../../src/ItemManager.cpp:588 ../../../src/MenuCharacter.cpp:351
```

I need %s to be in the genitive case. For example:

```
Ice = deigh
Ice Resistance = Comas-seasaimh an aghaidh deighe
```

Are the possible resistances a closed set? If so, there should be multiple string to translate without placeholder.

**Comment by Wuzzy2** [comment]
In Empyrean Campaign, %s is replaced by “Ice”, “Fire”, “Dark” or “Lightning”. This is used e.g. in the character menu.

I agree, the way the resistance strings are done is indeed wrong, it shows an English bias. You cannot chain words together in all languages like that, “word building” heavily depends on the language's grammar, and it just doesn't work that way like in English in many languages.

The correct way to deal with this is to force mods to provide the full term for each of the resistances as separate strings. The string “%s Resistance” should go, and be replaced by an individual resistance name provided by the mod.
For Empyrean Campaign, this would mean: “Ice Resistance”, “Fire Resistance”, “Dark Resistance” and “Lightning Resistance” as full strings for each of the resistances.

**Comment by dorkster** [comment]
I suppose these also fall into this trap?:

```
msg->get("Reduces the damage taken from \"%s\" elemental attacks.", eset->elements.list[j].name)
msg->get("%s Elemental Damage", eset->elements.list[pwr.trait_elemental].name)
```

Do we need to have separate versions of these for every element? Would something like these be more language-independent?:

```
"Resistance (%s)"
"Elemental Damage (%s)"
```

**Comment by Wuzzy2** [comment]
> Do we need to have separate versions of these for every element?

Yes, it would be better that way, and would solve grammar problems. Mods will likely not have a huge number of elements, so I don't think this is a problem. Empyrean Campaign only has 4 elements, so the overhead is small.

> Would something like these be more language-independent?:

Meh. Kinda. But it's kind of ugly and doesn't feel natural, it feels so constructed.

I suggest to use the same trick for %s Elemental Damage as for %s Resistance.

The string “Reduces the damage taken from \"%s\" elemental attacks." might be fine as-is, because the element type is in quotation marks.

**Comment by dorkster** [comment]
>But it's kind of ugly and doesn't feel natural, it feels so constructed.

I disagree. If anything, I think it's more organized to have the mechanic (resistance or damage) come before the type. We use a similar approach in other areas. For example, item quality is displayed as `Quality: %s`, avoiding the need to adhere to grammatical rules.

>The string “Reduces the damage taken from "%s" elemental attacks." might be fine as-is, because the element type is in quotation marks.

That's how I saw it. I think we have a few other strings that use a similar style, so we'll probably leave those alone.

**Comment by gunchleoc** [comment]
I'd be fine with a "Category: Type" or "Category (type)" approach, because while it doesn't look that natural, players can scan the information faster.
