### ISSUE TITLE
Linker Errors on Visual Studio Setup

### ISSUE THREAD

**Issue by abragon** [flareteam/flare-engine#1478]
Hello All,

Having setup the necessary libraries for the compiler on both a MinGW and Visual Studio build to encounter the same error has led me to the assumption that this occurs to my project setup itself. After debugging the source files to the point of my syntax capability. I was wondering if anyone with a working build has had knowledge or experienced LNK 2005 errors which I found when linking ..//distribution/Flare.Ico to the resource.h header. Would really appreciate any help.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"bool __cdecl PlatformDirCreate(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)"
 (?PlatformDirCreate@@YA_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in main.obj	flarev2	C:\Projects\flarev2\flarev2\PlatformWin32.obj	1	

Error	LNK2005	"bool __cdecl PlatformDirRemove(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?PlatformDirRemove@@YA_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in main.obj	flarev2	C:\Projects\flarev2\flarev2\PlatformWin32.obj	1	

Error	LNK2005	"void __cdecl PlatformInit(struct PlatformOptions_t *)" (?PlatformInit@@YAXPAUPlatformOptions_t@@@Z) already defined in main.obj	flarev2	C:\Projects\flarev2\flarev2\PlatformWin32.obj	1	

Error	LNK2005	"void __cdecl PlatformSetExitEventFilter(void)" (?PlatformSetExitEventFilter@@YAXXZ) already defined in main.obj	flarev2	C:\Projects\flarev2\flarev2\PlatformWin32.obj	1	

Error	LNK2005	"void __cdecl PlatformSetPaths(void)" (?PlatformSetPaths@@YAXXZ) already defined in main.obj	flarev2	C:\Projects\flarev2\flarev2\PlatformWin32.obj	1	

Error	LNK2005	"struct PlatformOptions_t PlatformOptions" (?PlatformOptions@@3UPlatformOptions_t@@A) already defined in main.obj	flarev2	C:\Projects\flarev2\flarev2\PlatformWin32.obj	1	

Error	LNK1169	one or more multiply defined symbols found	flarev2	C:\Projects\flarev2\Debug\flarev2.exe	1

**Comment by dorkster** [comment]
Hopefully, https://github.com/clintbellanger/flare-engine/commit/90eee482c188c69cd2d9c7a86c0b1755a38c0c9e should fix this problem.

**Comment by abragon** [comment]
I stumbled across a similar solution including guards so I initially set the resource.h as this error occurred with and w/o the ..//distribution//Flare.ico line in Platformwin32.cpp. Unfortunately adding it to Platformwin32.cpp does not change the result as of yet

**Comment by dorkster** [comment]
I should mention that it's highly recommended to use CMake to create proper Makefiles when building. I do this on Windows and am able to successfully run mingw32-make.exe.

**Comment by abragon** [comment]
Well I tried using cmake command but I do not believe I have linked libsdl/runtimsdl. Is there a procedure you could use for a proper setup as I am new to cmake. I've also tried using the gui but I believe that I must edit the Cmakelist.txt INCLUDE_DIRECTORIES(${SDL_INCLUDE_DIR}) but I don't know the syntax

**Comment by dorkster** [comment]
I don't remember entirely how I set everything up, but I essentially added the contents of the SDL2 mingw archives to my existing Code::Blocks installation of mingw.

Here's what my CMake config and %PATH% look like:
![mingw](https://cloud.githubusercontent.com/assets/913982/20433142/54920946-ad70-11e6-9047-6cab3fd0a4aa.png)

**Comment by abragon** [comment]
My issue with cmake is making the correct path syntax. It seems that documents on this are highly technical. My setup looks like this and I believe all I would need is to link the SDL2_INCLUDE_DIR appropriately
![capture-cmake](https://cloud.githubusercontent.com/assets/11580005/20472989/a92199dc-af8b-11e6-94d5-36887349063e.PNG)

**Comment by igorko** [comment]
SDL2_LIBRARY should point to lib file, not to folder, containig it.

**Comment by igorko** [comment]
Also after it says SDL2-image not found, check "Advanced" checkbox and you will see SDL2-image_lib and include_dir items. You should point them to lib and include dir. Press "Configure". It will again give the same error for SDL_mixer and SDL_ttf. Do the same. After that it should work.
