### ISSUE TITLE
setting screensize missing and not read from config file

### ISSUE THREAD

**Issue by scsijon** [flareteam/flare-engine#1485]
Downloaded a new engine yesterday after your help with a couple of changes (thank you), however for some reason I seem to have lost the ability to change screen matrixes when starting and even with the /root/config/flare/ settings.txt saying

display resolution. 640x480 minimum.
resolution_w=1914
resolution_h=1053

it's setting the resolution to 640x480 even in full screen, it's almost like it's lost contact to the config file for this, even though if I change other settings it's writing them out.

**Comment by dorkster** [comment]
"Resolution" in this case is a bit of a misnomer, and is an artifact from when the engine rendered at the same size as the window. In the current engine, these values refer only to the *window size*. The game is rendered on a "virtual" surface and then scaled to fit the window if needed.

The assets from the flare-game `fantasycore` mod are designed for 640x480, so we restrict the vertical size of our virtual surface to 480 pixels. This is done in

```
flare-game/mods/fantasycore/engine/resolutions.txt
```

with the `virtual_height` key. Try playing with this value and notice how it affects the game's rendering.

**Comment by scsijon** [comment]
ok that works, but what happened to the resolution box under configuration in version 0.19. It was a much better way of doing it. Could that be reimplemented?

**Comment by dorkster** [comment]
I'm not in favor of bringing the resolutions box back. The list in that box was populated by the different screen modes the user's display can do in fullscreen. However, we use `SDL_WINDOW_FULLSCREEN_DESKTOP` (which uses the player's desktop resolution) for fullscreen instead of changing display modes. And using those resolutions for windowed mode doesn't make much sense when the player can just resize the window like any other in their window manager.

Also, just in case there was a misunderstanding, the `virtual_height` setting I mentioned above is not meant to be edited by the players. Setting a virtual height lets game makers roughly control how much of the screen is visible at once, regardless of the player's physical monitor resolution. Before `virtual_height`, this was a notable problem when player's reported being able to see the entire map while on high DPI displays.

**Comment by scsijon** [comment]
On 03/13/2017 01:20 PM, Justin Jacobs wrote:
> I'm not in favor of bringing the resolutions box back. The list in that box was populated by the different screen modes the user's display can do in fullscreen. However, we use `SDL_WINDOW_FULLSCREEN_DESKTOP` (which uses the player's desktop resolution) for fullscreen instead of changing display modes. And using those resolutions for windowed mode doesn't make much sense when the player can just resize the window like any other in their window manager.
>
> Also, just in case there was a misunderstanding, the `virtual_height` setting I mentioned above is not meant to be edited by the players. Setting a virtual height lets game makers roughly control how much of the screen is visible at once, regardless of the player's physical monitor resolution. Before `virtual_height`, this was a notable problem when player's reported being able to see the entire map while on high DPI displays.
>

Ok I understand why your not in favour of the selection box, but.

To start with i'm not happy with fullscreen anyway as you can't switch 
screens (even with hotkeys) for some reason when it's turned on. Maybe 
something is wrong in the programming there also?

But sticking to a displayed area of 640x480 and a virtual-height of 480 
quite frankly only makes the game look 'crappy' when using larger 
displays like 24"widescreens and greater. Those other good few linux 
adventure and search-for type rpg games I have, all allow changes to 
suit the screen size if they don't do it internally. In Flare it just 
seems to increase the pixel display size and you end up with only an 
enlarged picture displayed, not a good look. Maybe a slider that allows 
setting of the virtual_height up to (say a max of) 768 is the fix. I'll 
try upping it on mine to 600 to start with and see if that's more suitable.

As it is, quite frankly, it's display makes it look like a 'Amateur 
hour' package. The 0.19 release looks far better than 0.20 anyday!

**Comment by dorkster** [comment]
Hmm, the idea of multiple virtual heights that we can switch between doesn't sound too bad. They would still be defined by the game maker, so there will still be that level of control. Now, there are two ways we could go about switching virtual heights:

- as you mentioned, a slider/list box in the video options to pick from the available sizes
- switch between them automatically based on the window size. For example, we would use a virtual height of 480 if the window height is >= 480 *and* < 600. After that, it'd switch to 600 and continue onwards in that fashion. I'm in favor of this option, but it will need some experimenting.

**Comment by scsijon** [comment]
I'll leave it to you to work it through as I wasn't aware you could do the second, however doing either would, I think, also require the package to 'ask' the video screen itself so you don't go outside it's available martrix's so I think at least to start with the first may be the easier to implement considering all the different platforms and video devices flare can run on.

**Comment by dorkster** [comment]
>Oh and I found that a max virtual_height of 925 is good for a 1920x1080x60hz LCD monitor, not sure why this value but 926 fails.

That's really strange. You should be able to set the virtual height to anything you want, regardless of your monitor's capabilities. For example, I can use a virtual height of 2160 despite only having a 1600x900 monitor. Do values *above* 926 work for you?

**Comment by dorkster** [comment]
I've implemented virtual height switching based on window size, and I think it works pretty well. Here's a [video ](https://youtu.be/eal_mueqj4o) demonstrating it with virtual heights of 480 and 600 (which I think are ideal for fantasycore's assets).

**Comment by scsijon** [comment]
sorry, but this doesn't seem to be working as per video, the sell/buy boxes are staying the same size even when I am changing overall window size, stuck at 480.
And just in case it was me, I git'd and rebuilt both flare-engine and flare-game again

**Comment by dorkster** [comment]
Maybe a dumb question, but are you sure you resized your window to something taller than 600 pixels?

**Comment by dorkster** [comment]
Oh wow, I'm sorry. I forgot to push the [necessary change](https://github.com/clintbellanger/flare-game/commit/727968a172bf5c59ece1a23589f39b33c8d17d25) to flare-game upstream.

**Comment by scsijon** [comment]
took it too full size (1920x1080), just manually upped the resolutions.txt to 600, no different, seems to be locked at 480 somewhere else. will search.

**Comment by scsijon** [comment]
OH and changing virtual_height above 925 fails until I set it to 1024, wonder if it's something to do with the available video modes? Yup, 1050, 1080 work but others between don't, these two have 59.5hz/60hz settings for the video in xorg, the others didn't. 
Maybe the slider would have been better after all as it seems that the engine switches to the default 480 if you pick any wrong sizes.

**Comment by dorkster** [comment]
resolutions.txt was the only file that needed changing, so it sounds like you're okay on that front.

I'm still perplexed as to why certain virtual heights aren't working for you. It should have nothing to do with you monitor's capable video modes. Can you try windowed mode?

Also, are you still getting this message when running Flare?:

>Settings: virtual_height is undefined. Setting it to 480.

**Comment by scsijon** [comment]
Settings error: Not after the latest git's, that seems to have sorted that out, I wonder if it was looking for them in the wrong resolutions.txt or settings.txt file?

My change to the resolutions.txt file works so I think i'll leave it as is for now if you don't mind. 

I tried putting two in as 900,480 and expanding the window, nothing happened, maybe it just doesn't like two for some reason. I use the internal intel video so maybe that effects it.

Oh yes and i've tried both windowed and fullscreen and no differances except as i've said before, with fullscreen I can't switch out of the program to another virtual desktop.

?Do you want to close this for now, or have you another idea to try, after all we can always reopen it if an idea ocurrs.

regards and thanks for all the help.

My next thing is to get my head around the Tiled package and see if I can find and then convert my old .png sets for the medieval town, cathedral and castle I built, modified and used back in the '90's. I wonder where that P2 is in my storeroom. Hopefully the drive is still ok, although it use to be easy to unstick them by swinging them horizontally, at least enough to copy everything off them. Nowadays drives just seem to die and that's it!

**Comment by dorkster** [comment]
Well, I tried `virtual_height=900,480` and had no problems on both a desktop Nvidia GPU and a modern laptop integrated Intel GPU. I'll have to dig out my old netbook that has an older Intel chip to test.

It's also strange to me that switching virtual desktops doesn't work in full screen for you. I used to have that problem with ioquake3 when it was built with SDL 1.2, but not anymore since the switch to SDL 2.

Anyway, you may want to [create a mod](https://github.com/clintbellanger/flare-engine/wiki/Creating-an-empty-mod) for your changes to resolutions.txt. That way, you can keep your copy of flare-game clean.

>My next thing is to get my head around the Tiled package and see if I can find and then convert my old .png sets for the medieval town, cathedral and castle I built, modified and used back in the '90's. I wonder where that P2 is in my storeroom. Hopefully the drive is still ok, although it use to be easy to unstick them by swinging them horizontally, at least enough to copy everything off them. Nowadays drives just seem to die and that's it!

That sounds really cool. Best of luck getting everything off that machine.

Thanks for being patient and doing all this testing. I'll leave this issue open since it obviously hasn't been resolved.
