### ISSUE TITLE
Weapon Swap

### ISSUE THREAD

**Issue by SarcrofS** [flareteam/flare-engine#1499]
How about implement a Weapon Swap like in Diablo 2 game?
Maybe a Equipment Swap changing all equipments will be more crazy 😄

**Comment by Rogni** [comment]
I'm sorry for my English.

IMHO. 
Changing all equipment immediately has several drawbacks.
1. Let's say the player has only one acceptable set of things and he wants to switch to the second weapon. Switching to the second weapon, he will remain naked.
2. If the character does not need a second weapon, he gets an additional 10 inventory points
