### ISSUE TITLE
 Window mode resize problems

### ISSUE THREAD

**Issue by crackedmind** [flareteam/flare-engine#1612]
Steps:
1) Launch game in window mode
2) Click maximize button

What we get:
- Window  maximized or nomalized, but text in menu was disappeared

Environment:
- Windows 10

![image](https://user-images.githubusercontent.com/1381503/37358199-819addea-26fb-11e8-9b68-a7a50c0f2feb.png)

**Comment by dorkster** [comment]
If you close the game and re-launch it, does the text re-appear, or is it still missing?

**Comment by crackedmind** [comment]
Re-appear, if i return in main menu from load menu, it's also re-appering. Some rendering problems, i guess

**Comment by crackedmind** [comment]
I can look at the code and fix it by myself, by i need time to learn your codebase :)

**Comment by dorkster** [comment]
Windows 7 works fine for me, so I wonder if this is a Windows 10 quirk. Maybe an issue with SDL_ttf?

**Comment by crackedmind** [comment]
Maybe, I can take a time to invertigate this and fix

**Comment by crackedmind** [comment]
Also it's happening with official distribution and my own compile with VC++ 2017

**Comment by dorkster** [comment]
If you can launch the flare.exe from the command prompt, try this:

```
flare.exe --renderer=sdl
```

**Comment by crackedmind** [comment]
Yep, bug didn't appear using software render

**Comment by dorkster** [comment]
Good to know! Then it's definitely a bug in either our `SDLHardwareRenderDevice` or SDL itself.

**Comment by crackedmind** [comment]
I'm building debug version and wiil look for this.

**Comment by dorkster** [comment]
For the meantime, you can permanently use the software renderer by editing `%APPDATA%\flare\config\settings.txt` and change "sdl_hardware" to "sdl" under "renderer".

**Comment by crackedmind** [comment]
Thanks, i found it already :)

**Comment by dorkster** [comment]
See if this problem persists with https://github.com/clintbellanger/flare-engine/commit/c90a00cc827ffe001eef818d2accbfcc19a042bc.

**Comment by crackedmind** [comment]
Problem partialy solved. Only visible text is redrawing. 
1) Start game
2) resize windows
3) open some menu (character, items, etc), text isn't rendering
4) resize again (without closing opened menus) and text will appear

**Comment by dorkster** [comment]
This [commit](https://github.com/clintbellanger/flare-engine/commit/0638b8acc7233894dc59395ff74335d2feacb93f) should fix it so that all labels get recached.

What's concerning is that the old caches are probably getting leaked for some reason. Since it seems to only be on Windows 10, and only when resizing the window, it's not that big of a deal.

**Comment by dorkster** [comment]
@crackedmind Can you verify if https://github.com/clintbellanger/flare-engine/commit/0638b8acc7233894dc59395ff74335d2feacb93f fixes this issue?

**Comment by igorko** [comment]
Reproduced under Window 10.
1. Start game in default resolution and windowed mode.
2. Go to Settings screen.
3. Click on Controls tab, then on Interface tab.
4. Scroll inside interface tab down and back.
5. Resize Window width only wth mouse.
6. Click on Controls tab. It has missing text.

**Comment by igorko** [comment]
Commenting https://github.com/flareteam/flare-engine/blob/master/src/WidgetLabel.cpp#L226
and https://github.com/flareteam/flare-engine/blob/master/src/WidgetLabel.cpp#L229 hides the issue, while commenting only https://github.com/flareteam/flare-engine/blob/master/src/WidgetLabel.cpp#L229 changes nothing. Looks like there is something wrong with image recaching.

**Comment by dorkster** [comment]
I'm able to reproduce this now in a Win 7 VM with sdl_hardware renderer and hardware surfaces enabled. It appears to affect all textures created as `SDL_TEXTUREACCESS_TARGET`, so places with non-WidgetLabel text and the minimap are affected as well. I'll investigate.

**Comment by dorkster** [comment]
Fix (hopefully) is up here: https://github.com/flareteam/flare-engine/commit/247b8cda8ff82d8bb672a83e3dbe73bfbb7d849f

In theory, we no longer need to recache text when the window is resized, but there isn't much harm in doing it anyway.

**Comment by igorko** [comment]
Confirming it's fixed!
