### ISSUE TITLE
Mac OS X release Flare.app linked … against Homebrew?

### ISSUE THREAD

**Issue by elosha** [flareteam/flare-engine#1619]
Hey, thanks for finally releasing 1.0 <3

I'm on Mac OS X 10.9 (Mavericks) on this machine, have Mac OS X 10.6.8 (Snow Leopard) on others. I don't use Homebrew, found it too messy, but have Mac Ports.

It seems the Mac OS X version you released is linked against libSDL2 provided by Homebrew.
> $./Flare
> dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
> Referenced from: /Applications/Spiele/Flare.app/Contents/MacOS/./Flare
> Reason: image not found
> Trace/BPT trap: 5

I then noticed that Flare.app brings libSDL2, but the binary looks at the typical installation path that Homebrew would use, and doesn’t use it’s own libraries.

Installing libSDL2 by Mac Ports and symlinking the Homebrew path doesn’t work:
> $./Flare
> dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
> Referenced from: /Applications/Spiele/Flare.app/Contents/MacOS/./Flare
> Reason: Incompatible library version: Flare requires version 9.0.0 or later, but libSDL2-2.0.0.dylib provides version 8.0.0
> Trace/BPT trap: 5

There’s also an official libSDL2 installer for the average user that installs into /Library/Frameworks:
https://www.libsdl.org/download-2.0.php

I tried to recompile flare-engine as an drop-in replacement for the app bundle binary (FLARE.app/Contents/MacOS/Flare) but didn't succeed, as flare-engine was then built for Linux paths, not for an .app bundle. I guess the link paths just weren't adjusted?

**Comment by dorkster** [comment]
FYI, a majority of the Mac port discussion has been in #1583. @tvleavitt recently supplied some documentation for his build here: https://github.com/clintbellanger/flare-engine/blob/master/distribution/macos/Flare%20DMG%20Build%20Documentation.pdf

**Comment by tvleavitt** [comment]
I've updated #1583.

**Comment by ludoza** [comment]
Using [this supertux](https://github.com/SuperTux/supertux/issues/60) issue as a reference point one can actually change the `./flare` to look for the `dylib`s in another directory.

At the moment `otool` report the need of the following `dylib`s:

```sh
otool -L flare
flare:
	/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 11.0.0, current version 11.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/usr/local/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib (compatibility version 3.0.0, current version 3.3.0)
	/usr/local/opt/sdl2_mixer/lib/libSDL2_mixer-2.0.0.dylib (compatibility version 3.0.0, current version 3.2.0)
	/usr/local/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

I will `cp` the needed `libSDL2_*.dylib` out of the homebrew path into `.libs/` run `brew uninstall --ignore-dependencies cmake libvorbis sdl2 sdl2_image sdl2_mixer sdl2_ttf` to make sure all dependancies is uninstalled and try to use `install_name_tool` tomorrow and give feedback.

Later,

**Comment by ludoza** [comment]
I also updated my progress on issue [#1583](https://github.com/flareteam/flare-engine/issues/1583#issuecomment-528562559).

@elosha have you tried to use `DYLD_LIBRARY_PATH=./lib ./flare` env variable to point the flare binary to the correct `dylib`s. Can you maybe test my `flare.dmg` package?

- [flare.dmg](https://gofile.io/?c=wV8fgB) (125M MD5 cb2db62f2c5ee4475481b399808f5a63)

**Comment by elosha** [comment]
@ludoza That doesn't work:
```
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Applications/Spiele/Flare.app/Contents/Resources/lib/libSDL2_image-2.0.0.dylib
  Reason: image not found
../MacOS/Flare: line 4: 25859 Trace/BPT trap: 5       DYLD_LIBRARY_PATH=./lib ./flare
```
It excpects the libSDL2's dependencies to be there, too. I wonder if one could just link them against system libraries.

**Comment by ludoza** [comment]
> It excpects the libSDL2's dependencies to be there, too. I wonder if one could just link them against system libraries.

Thanks for the test I modified the [`package_osx.sh`](https://github.com/flareteam/flare-engine/pull/1732/files#diff-0334eaa1a02ae1c13d9ad96a2d7bea64R72) to use `otool` to scan the dependencies after copying. And copy missed dependencies, so this should not happen again.

I'm not really a macos dev, so not sure how to link it against the system libraries. I feel the best strategy would be to bundle all the needed `dylib`s in the distributed package.
