### ISSUE TITLE
Custom "settings screen" layout not easy to create

### ISSUE THREAD

**Issue by nitramr** [flareteam/flare-engine#1667]
I'm trying to change settings page layout for a custom mod. I know that all layout definitions are described in:
mods/%modname%/menu/config.txt

Unfortunately all elements on that screen have to be positioned absolute to top left corner. For easy customization it would be nice to position all elements relative to a container. This is already done by e.g. powers.txt menu

Container will positioned by:
```
pos=340,0,640,832
align=center
```

Tab bar will positioned by:
```
tab_area=64,63,480,696
```

All other elements can be relative to parent container. It is easier just to move the container instead of every single element by hand.

**Comment by dorkster** [comment]
In a way, the widgets in the config menu are (mostly) aligned relative to a "container". This container is defined by the `menu_frame_width` and `menu_frame_height` values in `engine/resolutions.txt`. The "OK", "Defaults", "Cancel" buttons, however, are aligned relative to the screen, not the menu frame. The menu frame is also used for the New Game and Load Game menus. So maybe we can try these changes:

- Remove the "menu_frame" variables.
- Create a container that can be positioned anywhere like the smaller in-game menus. This container would contain all the widgets that were being positioned relative to the "menu_frame" variables. Each menu (New Game, Load Game, Configuration) would have their own definition for this container.
- Possibly create another container for the widgets that are currently being positioned relative to the screen. If we do this, it would be a good idea to provide some way to make the container map to the entire screen size to mimic the existing behavior.

**Comment by nitramr** [comment]
Alright, ```menu_frame_width``` and ```menu_frame_height``` does the trick. But this define just the size not the position.

I think option 2 would help a lot for free customization. At this moment your hint about ```menu_frame``` solved my current issue.

Futher I made a test and set ```required_width``` and ```required_height``` to full HD size but kept the ```menu_frame``` to old smaller size and the menu stay centered in game.

Thanks a lot!
