### ISSUE TITLE
unique items are not unique

### ISSUE THREAD

**Issue by x42** [flareteam/flare-engine#1672]
Items with `quality=unique` can still be present multiple times in the same game, and with some luck even dropped multiple times in the same loot!

`checkLoot` should check if a given unique item is on the floor already or present in the player's inventory and if so, remove it from the loot-list before iterating.

(That still allows unique items to be present multiple times via shared stash, but that is reasonable.)

**Comment by dorkster** [comment]
This is intentional. In reality, "unique" here is used as a synonym for "extremely rare". Perhaps we should use a different word.

**Comment by Sturwandan** [comment]
Maybe Epic? Or Rare? Though different games might even have several classes of rarity.

**Comment by bmorel** [comment]
rare and numeric limits are 2 different things:

* rarity is about drop chances
* numeric limits is about having a maximum number of an item handled by the game, that is, there could be only 10 items crafted by a (possibly lore-only) NPC

**Comment by dorkster** [comment]
This has been fixed to prevent multiple copies of a "unique" item in a single loot drop: 438f277 and https://github.com/flareteam/flare-game/commit/d1b3c7d7429adcecc9e4d5668fd3091671161985

As for multiple drops of an item in the same *play-through*, I consider that to be allowed behavior. So I'll close this now.
