### ISSUE TITLE
Monsters hidden by overhanging landscape.

### ISSUE THREAD

**Issue by daniel-santos** [flareteam/flare-engine#1674]
While the overhanging landscape is just part of fake 3d rendering, we need to be able to see monsters behind it.

**Comment by dorkster** [comment]
There are a couple approaches here:

1. Tilesets should have half-height walls that provide sort of a "cut-away" look at the level. The dungeon tileset in flare-game does this.
2. Add collision tiles that prevent entities from entering areas where they'd be obscured.
3. Likely the most difficult. Implement a way in the engine for detect when entities are obscured, and either make the wall translucent or render the entity above. I've tried the former before and it looked ugly. No idea on the latter, but I could see it working if the entity's color/alpha is changed.

**Comment by daniel-santos** [comment]
I'm most certainly opposed to making such obscured tiles non-traversable.  Sorry, but that's a terrible idea.

Rendering them on top w/o an alpha value would be terribly ugly indeed.  Classically, other games have either rendered them (or the foreground) as semi-transparent of have rendered an opaque outline of the sprite (not my favorite approach).

Another possible option is to render all of the overhanging tiles semi-transparently such the floor and objects underneath would also be visible.  I may now know what I'm talking about here though, I need to dig deeper into the engine and game to understand it better.

**Comment by dorkster** [comment]
Sorry if I was unclear, but it was the semi-transparent foreground rendering that I found ugly. The wall would be semi-transparent, but it would show the floor tile. It would look like the player could just walk off into the void.

Rendering the entity *above* the wall (changing the color/opacity to make them a ghost) is the option I haven't tried yet. I think Torchlight does this to some extent. Might be ugly as well.

Anyway, I thought of another idea. How about some sort of marker that would hover above the heads of entities to indicate their position? Maybe a white triangle for friendly and a red triangle for enemies, like so (mockup):

![screenshot_2018-09-27_20-21-06](https://user-images.githubusercontent.com/913982/46181395-798c0280-c293-11e8-9b9c-57765ad1acb0.png)

That would at least keep players from getting lost behind walls without being too visually distracting.

**Comment by daniel-santos** [comment]
That would certainly be a simple fix.  It's not as pretty as something where you can "see through walls" but it would be very helpful.  My only other thought is that when those skeletal archers cloak themselves, maybe use some triangle with the same opacity as the archer and maybe some less obvious color?  I dunno there.
