### ISSUE TITLE
Tooltips obstruct view of game entities

### ISSUE THREAD

**Issue by daniel-santos** [flareteam/flare-engine#1675]
When you get into a big fight and loot starts spewing everywhere you can no longer see who is beating you up or from what direction.  It's a great way to die -- the glory and all.  I was looking into this and it seems that the game state is rendered first and then the tooltips. :(

I can think of a few different ways to manage this, but this is first idea (and considers issue #1674).

1. We keep an "entities" mask buffer that can be just a single bit for each pixel of the rendering surface.
2. When entities are rendered, we populate the entities mask marking each pixel that is written to.
3. When rendering tooltips and overhanging landscape, we use this mask to decide rather to render each pixel as opaque or with an alpha value.

Actually, I haven't done graphics in a long time, so I can't quite remember how the pipeline works.

**Comment by dorkster** [comment]
Loot tooltips can be hidden by holding ALT. If turn off the "Always show loot labels" in the Interface configuration menu, they will always be hidden (and can be shown by holding ALT).

Per-pixel masking can be expensive considering it would likely be done without GPU assistance. I'd look at other ways of improving visibility, such as changing the tooltip graphics to have some transparency (see Diablo II) or dynamically fading tooltips out if hostile entities are near them.

Honestly, I'd probably file this under WONTFIX.

**Comment by daniel-santos** [comment]
Hrm.  Well I need to brush up on my graphics programming, I wouldn't want to do anything outside of the GPU pipeline. Maybe a simpler solution that's more elegant than hiding them completely when monsters are near is to give them an alternate alpha value when they are near?  Frankly, even setting a constant (non-opaque) alpha value would be better than leaving this unfixed.

**Comment by dorkster** [comment]
>Maybe a simpler solution that's more elegant than hiding them completely when monsters are near is to give them an alternate alpha value when they are near?

That's what I meant by "dynamically fading tooltips". The process would look like this:

1. For each piece of loot, get the nearest enemy.
2. Calculate the distance between the loot and the enemy.
3. Normalize the distance and use it to calculate the alpha value of the tooltip. We'd probably have a lower bound to prevent them from going completely invisible.

**Comment by dorkster** [comment]
I went for the simpler solution of just hiding the tooltips completely. It's less visually noisy than changing their opacity, and it's less performance intensive. Individual tooltips can still be seen by hovering over the pieces of loot with the cursor.

Modders can control the radius around an entity in which tooltips are hidden (or disable it outright) with the `hide_radius` setting in `engine/loot.txt`. The default value for this variable is 3 (same as `interact_distance` in `engine/misc.txt`..

**Comment by dorkster** [comment]
Just a quick update: You'll need to uncheck "Always show loot labels" to use the new dynamic hiding as of [this commit](https://github.com/flareteam/flare-engine/commit/99b189a1845736fd2b24c5bee9a4c347f331b0b5).
