### ISSUE TITLE
Game handged when clicked on obelisk in St.Maria Crypt

### ISSUE THREAD

**Issue by igorko** [flareteam/flare-engine#1678]
![image](https://user-images.githubusercontent.com/1015344/47903370-49381500-de8c-11e8-98a9-c9b6b1204151.png)

Also I hear looped sound of exiting map, and sound is crashing. Sound like few effects cause SDL sound channel overflow...

**Comment by igorko** [comment]
Also hangs if you click on it before spawning Seagate (when no sound is played.)

**Comment by dorkster** [comment]
This is a critical bug in my changes to the dialog system resulting in infinite recursion. I'll work on getting this fixed.

**Comment by dorkster** [comment]
Fixed (at least this particular instance) in https://github.com/flareteam/flare-engine/commit/811dba8530fa876f4a49924dabb8f21c1fe79c1c

@igorko I've also made an updated Windows build for you with the patch applied: https://drive.google.com/file/d/1M3sRJGAzaql7okK06eLlkPlZskgj0MQZ/view?usp=sharing
