### ISSUE TITLE
Character stops after moving into wall

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [flareteam/flare-engine#1683]
Running into walls (and maybe other obstacles) makes the character stop moving and turning.

To reproduce:
Version: Flare 1.08.17
With mouse move enabled [EDIT 2: after using a skill with shift also applied to the left mouse button] run into a wall while keeping the left mouse button pressed and move the cursor so the character would be able to move towards it ... just that he won't move or turn.
(Releasing the mouse button of pressing it again fixes this ... but that's not what the player should have do IMO)

May be related to ae6065d and 8fd7753

BTW: Great fixes! Feels much more smooth to play. Thanks a lot for those fast commits! ;)

EDIT:
This also seems to happen when running into monsters.
Getting hit (or going into "hit recovery" animation) seems to "unstuck" the character.

**Comment by dorkster** [comment]
So just to be clear, after running into a wall and keeping the mouse button pressed, you are unable to change trajectory? If so, I'm unable to reproduce this.

Running straight into a wall will stop movement, but adjusting my direction by 45 degrees allows me to run along the wall. This behavior is the same when using the keyboard controls.

**Comment by FeXoR-o-Illuria** [comment]
You are absolutely correct!
This issue only occurs when at any point before running into the obstacle I use shift to use a skill (keeping the left mouse button pressed during the hole process).

I didn't notice this before, sorry for the sloppy report.
I'll update it.
