### ISSUE TITLE
Consumed potions are not taken from the stack used

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [flareteam/flare-engine#1684]
Clicking a potion to drink it in the inventory doesn't always pick a potion from the stack clicked if multiple stacks of that type of potion is present in the inventory.
(AFAICT potions - and likely other consumable stackable items -  are always taken from the last stack in the inventory of that type)

To reproduce:
Without having full mana and 2 stacks of mana potions in your inventory drink from the first stack in your inventory. As a result one potion is taken from the second stack while the clicked stack stays untouched.

Not a big deal but still ... ;)

**Comment by FeXoR-o-Illuria** [comment]
I can't say this works for me :D
I checked out flare engine, build and launched but still with 2 stacks of mana potions the later stack's size is reduced regardless of the clicked stack.
AM I missing something?

**Comment by dorkster** [comment]
No idea why it's not working for you. I tested with two stacks of mana potions like you described, and was able to use and subtract from the first stack without affecting the later stack.

**Comment by FeXoR-o-Illuria** [comment]
Oops. That was because I used "git checkout" not "git pull" (I don't get the checkout command ;/).
Thanks, works like a charm. I also like the "autoequip" button.
Great changes, Thanks!
