### ISSUE TITLE
Creating an AppImage

### ISSUE THREAD

**Issue by demonpig** [flareteam/flare-engine#1689]
Is anyone interested in making an AppImage for Flare RPG?

I have been working on creating an AppImage of Flare RPG using openSUSE's Open Build Service just to see if it was doable. The newly built AppImage is known to work on openSUSE Leap 15.0 at the moment. I plan on doing some testing tomorrow to see what other OSs it will run on.

OBS Link: https://build.opensuse.org/package/show/home:demonpig:Games:AppImages/flare
AppImage: https://download.opensuse.org/repositories/home:/demonpig:/Games:/AppImages/AppImage/

Similar Issue: #1607

**Comment by dorkster** [comment]
I've updated my Linux build script to create an AppImage based on the script you posted. Not too surprisingly, `linuxdeployqt` appears to have done a better job of including the needed libs than my manual inspection of `ldd` output. So the AppImage will be replacing the binary tarball going forward.

The official AppImage will appear in a release candidate I plan on doing sometime in the next week or two. I'll close this issue when that goes live.
