### ISSUE TITLE
Should we prevent some keybindings from being changed?

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1690]
- The most glaring case is the Main1 action, bound by default to left mouse. If the player unbinds this, they can  end up unable to navigate the interface to change it back. The Main2 binding (aka right mouse) may also be a valid concern for future interface controls. I would propose locking the primary binding for these actions to the default left/right mouse buttons respectively. The secondary and joystick bindings would remain changeable.
- Other candidates are the Ctrl/Shift/Alt/Delete actions. I don't see much reason for players to be able to change these, as the actions themselves map to specific keyboard keys. Since they don't make sense for joysticks, I would propose locking the primary, secondary, *and* the joystick binding slots for these actions. These actions would always be mapped to the default keys.

**Comment by Wuzzy2** [comment]
Wow. If you can make FLARE completely unusable, not accepting even mouse clicks in the menu, then this is definitely a huge problem that needs to be addressed, somehow.

But I still would find it useful ot sill be able to re-bind the attack key, at least.
