### ISSUE TITLE
Jerking Ground and Character after getting to a hold

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [flareteam/flare-engine#1692]
After the Character stops first the Ground is jerking (looks like a slight tremor for about a second) and when becoming stable the Character (most of the time) starts to jerk around a bit (rapidly at first, then less often) until everything comes to a stable state after about 2 seconds. This all seems to be within one pixel range only for both the Ground and the Character.
Feels to me like some rounding of the character position is going on each turn that converges to the stable state which happens to take about 2 seconds on average.
(I do not expect this to be a feature but if it is I'd propose to do the rounding the frame/turn the character comes to a hod right away ;)

To reproduce:
- Move
- Stop moving and look closely on a non-uniform ground texture like grass (to better see the ground moving) or the character for about 3 seconds.

Flare 1.09.01

**Comment by FeXoR-o-Illuria** [comment]
Thanks, works like a charm!

I agree that with the default setting it only results in what one could call a minor graphical glitch.
Turning it to 100 reveals clearly that the function is not really thought through:
- The character can nearly leave the screen (somewhat expected with this "insane" value) BUT...
- Mouse input direction depends on cursor position relative to the centre of the screen, not character's position on screen resulting in a basically uncontrollable character because the player has no reference.

Before PPL get movement sickness leave this as is but as I see it this "feature" adds more confusion (reference point of mouse movement slightly off, small graphics glitch) than it can hope to prevent (motion sickness by rapid change of direction I guess).

Feel free to close this issue though since if I'm the only one noticing it's not worth the work I guess ;)

As always thanks for your fast, informed and elaborate reply! Flame on!

**Comment by dorkster** [comment]
Maybe the `camera_speed` variable should have an upper limit, perhaps based on the player's default speed. But I'll leave it as-is for now. There are plenty of variables in the Flare engine that can produce "bad" behavior when given extreme values, but we allow it. Let the modders be the judge of what's appropriate.
