### ISSUE TITLE
bluetooth joystick support [feature]

### ISSUE THREAD

**Issue by treymerkley** [flareteam/flare-engine#1699]
When playing, the game only recognizes my joystick if it's plugged in, even if the joystick is connected to my machine via bluetooth. Is there a way to set up bluetooth?

**Comment by dorkster** [comment]
We're generally at the mercy of SDL 2 when it comes to hardware support. So a few quick questions:

- What operating system are you using?
- What brand/model joystick is it?

**Comment by billywade** [comment]
Oof, yeah, I'd imagine that'd be a problem. I'm using Linux (Manjaro) and a SixAxis 3 PS3 controller.
