### ISSUE TITLE
Engine translations - no msgids for new mouse functions in options

### ISSUE THREAD

**Issue by Pawonashi** [flareteam/flare-engine#1710]
Could you place "Swap mouse movement button" and "Attack with mouse movement" and "Completed quests" strings so they could be translated? I couldn't find them in language files.

**Comment by nwtour** [comment]
See in engine.pl.po (not in data.pl.po)
$ grep -R 'Swap mouse movement button' *

flare-engine/mods/default/languages/engine.ru.po:msgid "Swap mouse movement button"
flare-engine/mods/default/languages/engine.gl.po:msgid "Swap mouse movement button"
flare-engine/mods/default/languages/engine.pl.po:msgid "Swap mouse movement button"

**Comment by dorkster** [comment]
It looks like they weren't in the engine file in v1.09.01 (which I presume @Pawonashi is using). But they are there in the current git master (and thus in v1.10 when it's released), so I'd consider this fixed.
