### ISSUE TITLE
Can not bind: E

### ISSUE THREAD

**Issue by ernierasta** [flareteam/flare-engine#1714]
In current master `E` key on US keyboard layout can not be bind. This key can not be bind in any layout (tested on my exotic one, where `L` is on this spot).

It looks like this is the only key, which have this problem.

**Comment by ernierasta** [comment]
It probably somehow related to blocking primary mouse, but it did not work well on my end. I will try to bring more details later.
Keybindings was reseted on first run, so it should be ok. I have tryied to bind every key and and up like this:
![2019-03-27-073718_grim](https://user-images.githubusercontent.com/956018/55055533-84b5c480-5063-11e9-9b8e-ce6621045d44.png)

**Comment by dorkster** [comment]
I found the bug. We're comparing against keycodes instead of scancodes in `SDLInputState::setKeybind()`.
