### ISSUE TITLE
Can not close HUD by clicking on x

### ISSUE THREAD

**Issue by ernierasta** [flareteam/flare-engine#1715]
Hi,
you maybe already know that, but probably 3f49913a5ded2d41caec266b6a142759f4dfe066 introduced bug. You can not close right sided hud (f.e. inventory) by clicking close (X) button.

**Comment by ernierasta** [comment]
wow, that was fast :-) BTW: great idea with this click zoom.

**Comment by dorkster** [comment]
Thanks. The minimap zoom was the one setting introduced in 1.09 that I would frequently change, whereas I barely touched the other settings past their initial configuration. So I wanted to keep the ability to change the minimap zoom without having to open the config menu.
