### ISSUE TITLE
flare android apk - enable a core mod to continue

### ISSUE THREAD

**Issue by qubodup** [flareteam/flare-engine#1724]
On android (Samsung G903F), I seem to be unable to get the game to run, even after extracting the mods to the folder pointed to in https://github.com/flareteam/flare-engine/wiki/Android-Port which in my case is 
![Screenshot_20190716-174033](https://user-images.githubusercontent.com/18312/61313820-861a2100-a7fb-11e9-8587-0e3074f18c23.png)
`/sdcard/Flare/mods/`

The issue is that the play button can't be used and the settings don't remember the mods I activate. Video of the issue: https://youtu.be/mSOehzUrFn8

I also tried `/storage/emulated/0/Android/data/org.flare.app/files/mods/` and `/sdcard/Android/data/org.flare.app/files/mods/` (all three separately as well as having the mod files and folders in all 3 locations at the same time). Same results all the time.

**Comment by dorkster** [comment]
From the Youtube video, it looks like you eventually got the mods in the correct location. The problem is that I didn't update the APK link on the wiki page. It should be for version 1.10. Link here: https://sourceforge.net/projects/flare-game/files/Android/flare-v1.10.apk/download

**Comment by qubodup** [comment]
@dorkster thank you, you are totally right.
