### ISSUE TITLE
Multiple background layer support

### ISSUE THREAD

**Issue by nitramr** [flareteam/flare-engine#1725]
Hi all,

after I saw an image of Rubberduck's grounds in OGA forum I got an idea.
It would be great to have some transition tiles from one ground tile into another one.

![Map](https://opengameart.org/sites/default/files/styles/medium/public/forum-attachments/ground_test02.png)
https://opengameart.org/forumtopic/new-potential-art-for-flare?page=1

BUT: If you had 8 different ground tiles, you would need any combination of tiles in any direction. There are many tiles.
It would be better to have a second background layer where you can add such a transition layer above the current background layer. This way, these new transition tiles can be partially transparent and you can see through the other floor partially.

Could be very helpful from gras to snow transition or you need just one gras tile and put different structure (e.g. dirt, stone) or flower tiles on top.

As I know Tiled support an endless amount of layers but Flare supports only 3 layers (background, collision, obejcts).
Would it be possible to support 1 or 2 more background layers to overlay ground tiles in Flare?
It can increase the variety of styles with same or lesser amount of tiles because of combinations.

What do you think about that idea?

**Comment by dorkster** [comment]
Good news: this is already possible! Take a look at any of the snow maps, such as `tiled/empyrean_campaign/lake_kuuma.tmx`. Arbitrary layers can be placed both above and below the `object` layer. The `background_fringe` layer has been used for exactly what you described, since the snow tileset has transition tiles.

**Comment by nitramr** [comment]
Hi Dorkster,

great! Thanks for your fast response.
