### ISSUE TITLE
Allow opening game menu with mouse

### ISSUE THREAD

**Issue by jtrees** [flareteam/flare-engine#1735]
In my opinion the game should be playable using only a mouse. I think this is already mostly the case but accessing the game menu (e.g. to change settings or exit the game) is currently not possible this way.

I propose adding a GUI element to the HUD that can be clicked on to bring up the menu.

**Comment by dorkster** [comment]
I like this idea. Personally, I'd most like to see it on the mobile version because my phone's back button is broken, but there's no reason not to have such a feature for all platforms.
