### ISSUE TITLE
Minimap to be gradually revealed

### ISSUE THREAD

**Issue by McSinyx** [flareteam/flare-engine#1741]
Hi,

I've been playing Flare repeatedly for quite a few years now, and my biggest struggle is to navigate through all quests and maps.  Recently I've just started playing Torchlight II and don't have that problem, largely thanks to the minimap which shows where I've been.  Here are the screenshots of the minimap in Torchlight II:

![corner](https://user-images.githubusercontent.com/13689192/67158777-782dec00-f366-11e9-853d-c643505ae1e6.png)
![overlay](https://user-images.githubusercontent.com/13689192/67158776-782dec00-f366-11e9-837a-10da9afe0f2c.png)

I'm not sure if not having revealing minimap in Flare was its design in the first place, since the mechanics of the two games are different (Torchlight does not resurrect enemies when revisiting a map); but if it is possible, I'd really appreciate to have the minimaps that *remember* where I've been.  Furthermore, overlaid minimaps as shown in the screenshot above would be really convenient for big and complicated maps.

**Comment by m7600** [comment]
Hi,

If you are open to suggestions, I think it that it would be best if this feature was optional. That is, it could be a property of engine/misc.txt that takes true or false as a value, so that modders/players have the choice of using this feature or not.

**Comment by dorkster** [comment]
Implemented via #1780
