### ISSUE TITLE
Allow to cycle through tabs

### ISSUE THREAD

**Issue by basxto** [flareteam/flare-engine#1745]
It would be nice to have two shortcuts to cycle through tabs (to the left and to the right).
This is especially helpful for gamepads, but can also be used to use the keyboard more.

**Comment by ate088** [comment]
Hi, if this feature gets implemented, may I request that it is something you can enable or disable in the engine settings test file? 

My reason is this: In FLARE every class has access to every skill, unlike in Diablo II where each class has it's own unique skill trees. However, I have managed to "hack" 3 classes that have a separate powers menu each, by hiding all the tabs to make the powers in the other tabs inaccessible.  Adding this feature would basically ruin my setup, so it would be nice if this was something I can opt out of.

**Comment by dorkster** [comment]
@ate088 FYI, you can assign individual power trees to classes with the [power_tree](https://github.com/flareteam/flare-engine/wiki/Attribute-Reference#enginesettings-classes) property. So for a warrior class, you could have something like:

```
power_tree=powers/trees/warrior.txt
```
