### ISSUE TITLE
Debian Flare package lacks tag "game::rpg"

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [flareteam/flare-engine#1746]
The [Debian flare package](https://packages.debian.org/buster/flare) lacks the tag `game::rpg`.
This may be intentional (maybe because AFAIK it defines itself as action RPG) but I think it will be easier to find for those searching by tags (and is IMO the best fitting tag available for Flare).

(Feel free to delete this if this is the wrong place)

**Comment by dorkster** [comment]
I think `game::rpg` is an appropriate tag for Flare.

However, this is ultimately the decision of the Debian packager(s). So I would suggest letting them know directly.

**Comment by FeXoR-o-Illuria** [comment]
Is the FLARE package maintainer still @manuelafm ?

**Comment by McSinyx** [comment]
There are maintainers emails on the right side of the package page, I'm not sure how recent it is updated though.

**Comment by manuelafm** [comment]
> Is the FLARE package maintainer still @manuelafm ?

@FeXoR-o-Illuria : In Debian (and I suspect that Ubuntu and other derivatives) yes, I am.

**Comment by FeXoR-o-Illuria** [comment]
Great, @manuelafm :D

So what do you think about my proposal?

**Comment by manuelafm** [comment]
> Great, @manuelafm :D
> 
> So what do you think about my proposal?

Sorry for the delay, it's been a difficult year...

Done now, I added these tags and a few other:
https://debtags.debian.org/reports/maint/mafm@debian.org#flare

I think that this can be closed :)
