### ISSUE TITLE
Zola is dead... Or not?

### ISSUE THREAD

**Issue by vgaming** [flareteam/flare-engine#1754]
Hi, I just got a very interesting bug with zombie and dead enemies.

When I summon a zombie to fight with Zola (and other AI enemies), zombie attacks the already dead Zola from time to time. At first I thought it's a bug similar to https://github.com/flareteam/flare-engine/issues/1749 or https://github.com/flareteam/flare-game/issues/697. But upon playing more, I suspect it's something different. The specifics of Zola is that:

* I already encountered my zombie attacking dead Zola 2 or 3 times in the last days, whereas it only happened once on all other units combined.
* Zola actually has positive HP! See the screenshot 
![2020 05 01_16:20:08](https://user-images.githubusercontent.com/33452702/80812184-b767b000-8bc7-11ea-9f25-7bea2b5fc96c.png)

Does flare have a separate flag for "being dead" and HP number? Does Zola have some healing powers, or "HP drain" attack that would make him dead at one moment but be HP-positive after his bullet hits a target later? Any other thoughts?

**Comment by dorkster** [comment]
>Does Zola have some healing powers, or "HP drain" attack that would make him dead at one moment but be HP-positive after his bullet hits a target later?

I think this is it! And looking at #1749, the dead zombie in that screenshot *also* has an HP stealing power. Preventing HP/MP steals once an entity hits zero HP seems to be an appropriate fix.

**Comment by vgaming** [comment]
@dorkster should the allied zombie also only attack "non-dead" enemies, as opposed to "HP-positive"? If there's indeed a boolean flag for being dead, using it seems like the more canonical way for zombie target detection?

**Comment by vgaming** [comment]
Awesome that the reason was found and the fix is being made though!:blush:

**Comment by dorkster** [comment]
As far as the engine is concerned, "HP-positive" is equivalent to "non-dead". There is a "corpse" flag in the StatBlock, but it is only set to true once an entity has finished its death animation. We only want allies to attack living entities, not those that are in the process of dying or have already died.

**Comment by vgaming** [comment]
Thanks for the explanation!
