### ISSUE TITLE
How to use developer console? Needs docs?

### ISSUE THREAD

**Issue by kevzettler** [flareteam/flare-engine#1759]
I'm aware of the developer console from:
https://github.com/flareteam/flare-engine/wiki/Developer-Console

But the documentation is a bit lacking. I am aware there is a `help` menu with a few commands. It says you can execute events with the developer console and gives an example of a message event. 

How do know what the other events are and the arguments they accept?

**Comment by dorkster** [comment]
The `exec` command uses the [Event properties](https://github.com/flareteam/flare-engine/wiki/Attribute-Reference#eventmanager) as commands. Here are a few more common examples:

```
# teleport to perdition harbor
exec intermap=maps/perdition_harbor.txt

# add a Health Potion to the inventory
exec reward_item=2,1

# gain 100 XP
exec reward_xp=100

# set a campaign status
exec set_status=my_status

# reset the character's XP, stats, skills to level 1
exec respec=xp
```

**Comment by kevzettler** [comment]
thanks @dorkster I will add to the wiki

**Comment by kevzettler** [comment]
@dorkster how do I know what `event.type | string | ` are availble?

**Comment by dorkster** [comment]
`event.type` is the same as `npc.type` and `enemygroup.type`. These keys are added to the corresponding objects when exporting a map in Tiled. The engine doesn't do anything with them (hence why the docs say they're ignored), but we check them in the parser as to not cause an "unknown key" error.

**Comment by kevzettler** [comment]
@dorkster sorry I think I asked the wrong thing regarding `event.type` 

What i really mean is where did you find that list of exec commands at:
https://github.com/flareteam/flare-engine/issues/1759#issuecomment-629052218

like where would I know I could use: 
`exec reward_item=2,1`

is there a list of exec commands anywhere?

**Comment by dorkster** [comment]
The Event properties I linked above is essentially the list of commands. For example, if we look at this example in the documentation:

>event.**reward_item** | item_id, int : Item, Quantity | Reward hero with y number of item x.

Translated to an exec command:

```
exec reward_item=item_id,int
```

You would replace **item_id** with the ID of the item you want to give the player, and replace the **int** with the quantity.

Many of the commands don't do anything by themselves, such as `requires_status`. You can string these commands together to construct complete Events by putting a space between each command. If the command would contain a space, you can wrap it in double quotes ("). Ex:

```
exec requires_status=my_status "msg=my_status is active"
```

Not all commands are supported. Here's a list of the ones that are not:

- `type`
- `activate`
- `location`
- `hotspot`
- `cooldown`
- `delay`
- `reachable_from`

**Comment by kevzettler** [comment]
Ok thank you for the clarification
