### ISSUE TITLE
Emscripten port: Fullscreen/resizing canvas?

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1760]
Something that the Emscripten port lacks is a way to go fullscreen. Would be nice to have this feature since most people don't want to play in a small browser frame.

**Comment by ate088** [comment]
People were requesting this on Ghostlore as well :)

**Comment by dorkster** [comment]
Forgot to close this when https://github.com/flareteam/flare-engine/commit/018b55850a23adb9ee85926cbe2b588cdf898631 was implemented.
