### ISSUE TITLE
Segfault on startup (Fedora 31-34; Flare v1.07)

### ISSUE THREAD

**Issue by 1-byte-man** [flareteam/flare-engine#1762]
System: Fedora 31.
Arch: x86_64
Flare version: 1.07
Console logs: 
```
[german06@powercanaima ~]$ flare 
INFO: Flare 1.07 (Linux)
INFO: Active mods: default, fantasycore (1.07), empyrean_campaign (1.07)
INFO: MessageEngine: Using language 'en'
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
INFO: InputState: No joysticks were found.
INFO: Using Render Device: SDLHardwareRenderDevice (hardware, SDL 2, x11)
INFO: RenderDevice: 1 display(s), using display 0 (1024x600 @ 60hz)
INFO: RenderDevice: Internal render size is 640x480
INFO: RenderDevice: Window size is 640x480
INFO: RenderDevice: Fullscreen=0, Hardware surfaces=1, Vsync=1, Texture Filter=1
INFO: RenderDevice: Display DPI is 117.920082
INFO: GameStateCutscene: Loading cutscene 'cutscenes/intro.txt'
INFO: GameStateCutscene: No scenes defined in cutscene file cutscenes/intro.txt
Segmentation fault (`core' generado)
```

**Comment by dorkster** [comment]
Looks like an issue with Fedora's packaging. Instead of including the fonts we have in our repo, the packager created symlinks to system-wide fonts. This is fine, I suppose, but they didn't mark `liberation-fonts` as a dependency. So there's two solutions for you here:

## 1: Install a correct copy of the game data for the local user (recommended)

- Download the Flare 1.07 game repo tarball: https://github.com/flareteam/flare-game/archive/v1.07.tar.gz
- Extract it, and copy the content of the `mods` directory to `~/.local/share/flare/mods/`

Mods installed in `~/.local/share/flare/mods/` should take priority over those installed system-wide.

## 2: Install liberation-fonts and fix the symlink

Only do this if you're okay with adding a symlink in `/usr`. There's always the risk of a package conflict in the future.
```
sudo dnf install liberation-fonts
# the Flare package has symlinks that don't work with the latest liberation-fonts package, so fix them by creating another symlink
sudo ln -s /usr/share/fonts/liberation-sans/ /usr/share/fonts/liberation/
```

**Comment by dorkster** [comment]
By the way, the crash when fonts are missing [has since been fixed](https://github.com/flareteam/flare-engine/commit/19556248e2b7851348189f1f984f5307eec3b9c2). There will be blank spots where text would be if no font can be loaded, but there should no longer be a segfault.

**Comment by 1-byte-man** [comment]
Ok, all works. I'm gonna report this to the fedora packaging team to fix it ASAP. Thx

**Comment by eufordia** [comment]
Same problem in Fedora 33:
`$ rpm -qa |grep flare
flare-engine-1.07-6.fc33.x86_64
flare-1.07-7.fc33.noarch`


`$ flare
INFO: Flare 1.07 (Linux)
INFO: Active mods: default, fantasycore (1.07), empyrean_campaign (1.07)
INFO: MessageEngine: Using language 'en'
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
ERROR: FontEngine: TTF_OpenFont: SDL_RWFromFile(): No file or no mode specified
INFO: InputState: No joysticks were found.
INFO: Using Render Device: SDLHardwareRenderDevice (hardware, SDL 2, x11)
INFO: RenderDevice: 2 display(s), using display 0 (1920x1080 @ 50hz)
INFO: RenderDevice: Internal render size is 640x480
INFO: RenderDevice: Window size is 640x480
INFO: RenderDevice: Fullscreen=0, Hardware surfaces=1, Vsync=1, Texture Filter=1
INFO: RenderDevice: Display DPI is 101.599998
INFO: SoundManager: Using SDLSoundManager (SDL2, pulseaudio)
INFO: GameStateCutscene: Loading cutscene 'cutscenes/intro.txt'
INFO: GameStateCutscene: No scenes defined in cutscene file cutscenes/intro.txt
Segmentation fault (core dumped)
`

The package liberation-fonts is installed:

`# dnf install liberation-fonts
Ultima verifica della scadenza dei metadati: 0:18:50 fa il mar 6 apr 2021, 21:16:56.
Package liberation-fonts-1:2.1.3-1.fc33.noarch is already installed.`

and the folder /usr/share/fonts/liberation-sans/ already exits:
`# pwd
/usr/share/fonts`

`# ll -d liberation*
drwxr-xr-x. 1 root root 246  3 mar 17.10 liberation-mono
drwxr-xr-x. 1 root root 246  3 mar 17.10 liberation-sans
drwxr-xr-x. 1 root root 254  3 mar 17.10 liberation-serif`

**Comment by dorkster** [comment]
Looks like the reported bug got closed due to end-of-life. I resubmitted it: https://bugzilla.redhat.com/show_bug.cgi?id=1947228

**Comment by dorkster** [comment]
I missed it by about two weeks, but there was some [response from the maintainer](https://bugzilla.redhat.com/show_bug.cgi?id=2006663#c2) on the flare-game package bug tracker! It does look like they might not be interested in continuing to be the maintainer. I'd offer, but I feel like it would be better to have someone who's actually familiar with packaging on Fedora, or at least uses Fedora as their main OS.

**Comment by Ablu** [comment]
Builds with a fix (and update) are submitted for rawhide. Sorry for taking that long to fix it! Thanks to @dorkster for the patches.
