### ISSUE TITLE
no VC++ solution?

### ISSUE THREAD

**Issue by TanisTheRed** [flareteam/flare-engine#1763]
You say this can be built with VC++ but there is no solution included anywhere?

**Comment by dorkster** [comment]
You must use [CMake](https://cmake.org/download/) to generate the build files. 

1. Using the CMake GUI, set the source code directory to that of flare-engine
2. Press "Configure".
3. There it will let you select which generator you want to use, which will be a version of VC in your case.
4. Set `CMAKE_BUILD_TYPE` to either `Debug` or `Release`.
a. You may need to fill out other variables if the generator wasn't able to find things like SDL
5. Click "Generate"

**Comment by TanisTheRed** [comment]
I followed the instructions on the site:


#get the vcpkg code
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
#bootstrap vcpkg
./bootstrap-vcpkg.bat
#install the dependencies (for 64bit builds, you can use x86-windows triplet instead if you want 32bit)
./vcpkg install sdl2:x64-windows sdl2-image:x64-windows sdl2-mixer:x64-windows sdl2-ttf:x64-windows

then when I try to run cmake gui it says it can't find the files for anything after the sdl2 main's?  Any ideas?

________________________________

**Comment by dorkster** [comment]
Ah, I forgot those instructions were there. I never used VC, so I've been doing Windows builds with MinGW.

There's a bit on the vcpkg page that might help:

>In order to use vcpkg with CMake outside of an IDE, you can use the toolchain file:

> cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
> cmake --build [build directory]

So if you can find that vcpkg.cmake file on your system, then add a file path entry for `CMAKE_TOOLCHAIN_FILE` that points to it during step 4 in my first comment. That seems like it should help CMake find the libraries you downloaded with vcpkg.

**Comment by TanisTheRed** [comment]
Ok I figured it out.  After installing and running the commands for the vckpg the way you get the toolchain to work is when you start cmake there is a selection "specific toolchain file for cross-compiling" then you put in the path to vcpkg as below.  Trying to create your own path after the fact for some reason does not work.  Thank you for your help, I was really struggling to just get the project created.

________________________________

**Comment by dorkster** [comment]
Interesting. I don't think the VC part of our documentation needs updating, as it specifies using the command line over the GUI for cmake. I think there's issues when trying to set `CMAKE_TOOLCHAIN_FILE` after running cmake once.
