### ISSUE TITLE
Can not compile and run in VS 2019

### ISSUE THREAD

**Issue by TanisTheRed** [flareteam/flare-engine#1764]
Sadly I have tried everything and there is no straight forward guide that actually works to even get the base engine to compile and run in VS 2019.

I was helped with cmake even though I had to alter the guide and process to even make the solution.  

After that I had to manually delete the post-build configuration section to avoid the cmd.exe exit with error 1.

After that it will seem to compile but if you try to run it always crashes saying can't find sdl2.dll even though I followed the 5 different versions of the vcpkg setup steps.

So have anyone actually created, compiled and run this engine in VS 2019 or any visual studio at all?  If so can we please get an update accurate working guide of how to even get started with this engine?

**Comment by dorkster** [comment]
It looks like it might have compiled fine, but just can't locate the dynamic libraries. We ship the Windows binaries with these (albeit the MinGW versions) in the same directory as flare.exe:

```
SDL2.dll
SDL2_image.dll
SDL2_mixer.dll
SDL2_ttf.dll
libFLAC-8.dll
libfreetype-6.dll
libjpeg-9.dll
libmodplug-1.dll
libmpg123-0.dll
libogg-0.dll
libopusfile-0.dll
libopus-0.dll
libpng16-16.dll
libtiff-5.dll
libvorbisfile-3.dll
libvorbis-0.dll
libwebp-7.dll
zlib1.dll
```

You could try hunting these down in you vcpkg installation. Maybe we there is something we should have in our CMakeLists.txt that copies these files automatically in such scenarios?

**Comment by TanisTheRed** [comment]
Getting cmake to work to find those in the vcpkg was tricky but some are there when I compile with VC.  with the Flare.exe it only lists these:

brotlicommon.dll
brotlidec.dll
bz2d.dll
freetyped.dll
libpng16d.dll
sdl2_image.dll
sdl2_mixer.dll
sdl2_tff.dll
sdl2d.dll
zlibd1.dll

So even though I did't have all the ones you listed at least the sdl2.dll is there.  I did go through the vcpkg and found all the other ones you listed and copied them into the bin/debug folder with the flare.exe and its still saying can't find the sdl2.dll?

________________________________

**Comment by TanisTheRed** [comment]
Ok besides missing the ones I listed before I was wrong I had a SDL2d.dll and no sdl2.dll which I did find in the vcpkg and copied that over.  That got it to start to run and these are the errors I see now:

INFO: Flare 1.11.56 (Windows)
ERROR: ModManager: Error during loadModList() -- couldn't open mods.txt, to be located at:
ERROR: C:\Users\tanis\AppData\Roaming\flare\config\mods.txt
mods\mods.txt
INFO: Active mods: default
INFO: MessageEngine: Using language 'en'
ERROR: EngineSettings: save_prefix not found in engine/misc.txt, setting to 'default'. This may cause save file conflicts between games that have no save_prefix.
ERROR: FileParser: Could not open text file: engine/loot.txt: No such file or directory!
ERROR: FileParser: Could not open text file: engine/xp_table.txt: No such file or directory!
ERROR: EngineSettings: No XP table defined.
INFO: InputState: No joysticks were found.
INFO: Using Render Device: SDLHardwareRenderDevice (hardware, SDL 2, windows)
INFO: RenderDevice: 2 display(s), using display 0 (1920x1080 @ 60hz)
INFO: RenderDevice: Internal render size is 1089x600
INFO: RenderDevice: Window size is 1920x1057
INFO: RenderDevice: Fullscreen=0, Hardware surfaces=1, Vsync=1, Texture Filter=1
INFO: RenderDevice: Display DPI is 96.000000
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 1 time:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/icons/icons.png'. Invalid window
INFO: SoundManager: Using SDLSoundManager (SDL2, wasapi)
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 2 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/menus/buttons/button_default.png'. Invalid window
ERROR: ModManager: Game data is either missing or misconfigured. Deleting 'C:\Users\tanis\AppData\Roaming\flare\config/mods.txt' in attempt to recover.
Filesystem::removeFile (C:\Users\tanis\AppData\Roaming\flare\config\mods.txt): No such file or directory

D:\MagiQuest MMORPG - 2004_files\LI Source Control Project\Flare versions\New folder\bin\Debug\flare.exe (process 5356) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .






________________________________

**Comment by TanisTheRed** [comment]
Also the mods are not in the right location.  I had to copy them under users, and I also had to copy the mod.txt into the config location to bypass those errors.  Once I do that I get all these render magic and then failed push button:

INFO: Flare 1.11.56 (Windows)
INFO: Active mods: default, fantasycore (1.11), empyrean_campaign (1.11)
INFO: MessageEngine: Using language 'en'
INFO: InputState: No joysticks were found.
INFO: Using Render Device: SDLHardwareRenderDevice (hardware, SDL 2, windows)
INFO: RenderDevice: 2 display(s), using display 0 (1920x1080 @ 60hz)
INFO: RenderDevice: Internal render size is 1089x600
INFO: RenderDevice: Window size is 1920x1057
INFO: RenderDevice: Fullscreen=0, Hardware surfaces=1, Vsync=1, Texture Filter=1
INFO: RenderDevice: Display DPI is 96.000000
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 1 time:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/icons/icons.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 2 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/icons/icons_empyrean.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 3 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/icons/icons_crafting.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 4 times:
  'renderer && renderer->magic == &renderer_magic'

WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 5 times:
  'renderer && renderer->magic == &renderer_magic'

WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 6 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/icons/icons_overlay.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 7 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/icons/icons.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 8 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_normal.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 9 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_interact.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 10 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_interact.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 11 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_attack.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 12 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_lhp_normal.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 13 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_lhp_interact.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 14 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_lhp_interact.png'. Invalid window
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 15 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/cursors/cursor_lhp_attack.png'. Invalid window
INFO: SoundManager: Using SDLSoundManager (SDL2, wasapi)
WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 16 times:
  'renderer && renderer->magic == &renderer_magic'

WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 17 times:
  'renderer && renderer->magic == &renderer_magic'

WARN:

Assertion failure at SDL_CreateTextureFromSurface_REAL (C:\Users\tanis\vcpkg\buildtrees\sdl2\src\SDL2-2-ac07e8117e.clean\src\render\SDL_render.c:1151), triggered 18 times:
  'renderer && renderer->magic == &renderer_magic'

ERROR: SDLHardwareRenderDevice: Couldn't load image: 'images/menus/buttons/button_default.png'. Invalid window
ERROR: ModManager: Game data is either missing or misconfigured. Deleting 'C:\Users\tanis\AppData\Roaming\flare\config/mods.txt' in attempt to recover.

D:\MagiQuest MMORPG - 2004_files\LI Source Control Project\Flare versions\New folder\bin\Debug\flare.exe (process 10940) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .



________________________________

**Comment by dorkster** [comment]
The "Invalid window" message is a sign that SDL_CreateRenderer failed. You could try the launching flare.exe with either 
```
--renderer=sdl
```
or 
```
--safe-video
```
If you don't want to use the command line options, you could edit the config file at `C:\Users\tanis\AppData\Roaming\flare\config\settings.txt` and set the following:

```
fullscreen=0
hwsurface=0
vsync=0
texture_filter=0
renderer=sdl
```

**Comment by TanisTheRed** [comment]
Ok I restarted from scratch and here is where I am now:

order I did:

*** path can not have any SPACES in it

git hub for dirent
git hub for vcpkg
- run all the commands and it built and integrated without any errors

git hub for flare-engine
git hub for flare-game

did the "cmake ." command and got the following error!

-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
CMake Error at CMakeLists.txt:67 (Message):
  Couldn't find SDL2 development files.  On Debian-based systems (such as
  Ubuntu) you should install the 'libsdl2-dev' package.


-- Configuring incomplete, errors occurred!
See also "D:/Flare-projects/flare-engine/CMakeFiles/CMakeOutput.log".
See also "D:/Flare-projects/flare-engine/CMakeFiles/CMakeError.log".


so skipped that and used cmake gui
 pointing toolchain to the vcpkg.cmake

only error was pthread.h - not found

opened the solution and everything built without errors

trying to run I get can't find sdl2.dll and there is none with the exe, but there is a sdl2d.dll.

copied the sdl2.dll they listed on thier site into the folder with the .exe

then ran and got flare unable to launch properly and should use safe video.

clicked safe video and crashed in sdlsoftearerenderdevice on icons.png

in the dos window also got errors stating can't open mods.txt because its not in the config folder.

Copied the mods.txt to the location

reran and got the save video thing  again and clicked reset count, now I get the assertion
failure message for renderer_magic

eventually clicking through tons of those I get the couldn't load image button_default.png

using email from git was told this:
If you don't want to use the command line options, you could edit the config file at C:\Users\tanis\AppData\Roaming\flare\config\settings.txt and set the following:

fullscreen=0
hwsurface=0
vsync=0
texture_filter=0
renderer=sdl


I changed mine to match as mine were
fullscreen=0
hwsurface=1
vsync=1
texture_filter=1
renderer=sdl_hardware

I have to copy the mods.txt to the config location each time I run.

still get exception in the sldsoftwarerenderdevice.cpp for images/icons/icons.png

If I restart and click safe video I crash in same place but for "images/icons/icons_empyrean.png" now




________________________________

**Comment by dorkster** [comment]
sdl2d.dll is just the debug version of sdl2.dll. So if you're doing a debug build, you should be using sdl2d.dll

You also don't have to copy mods.txt to your config directory every time. You only need to copy it to the same mods/ directory that has "default", "fantasycore", etc. (and even then, it's optional).

**Comment by TanisTheRed** [comment]
Ok switching to build release gets it to load and run though the sound does not work saying .ogg is unrecognized audio format?  Any idea to fix that last piece?

________________________________

**Comment by dorkster** [comment]
Maybe you need to copy the libogg, libopus, and libvorbis DLLs to your flare.exe directory? I would assume they got pulled in with SDL_mixer. They could be optional dependencies, though, so you may need to get them with vcpkg.

**Comment by TanisTheRed** [comment]
I tried that from the previous post of copying all those from the vcpkg but still same error. =(

________________________________

**Comment by dorkster** [comment]
I'm sorry I don't have a solution for the VC issues, but I have added [instructions for using MSYS/MinGW](https://github.com/flareteam/flare-engine/blob/master/INSTALL.engine.md#msys2--mingw). This is our official method of creating Windows builds, and may be the only option if VC just doesn't want to cooperate.

**Comment by TanisTheRed** [comment]
I got everything to work and compile and run except for the sound.  Comparing what is in the vcpkg to what comes with the already built game (which does work with sound on my pc) is the vcpkg files are different.  I am trying to gather and build them individually since it appears that the vcpkg may be out of date or something as the files are different.  I can't just drag and drop the ones from the game into my version as that causes the game to fail all together.  Hopefully either I can find and recompile later versions or if someone else has a different version of vcpkg or a different way to do this.

________________________________

**Comment by TanisTheRed** [comment]
Still trying to figure this out.  Out of the 4 files in vcpkg sdl2, sdl2-image and sdl2-ttf the vcpkg all have later versions.  the sdl2-mixer though is marked as the same version as what you have in your released version of the game, though the files sizes are drastically different.

________________________________

**Comment by dorkster** [comment]
The files in the released version of the game are all the MinGW versions, so they are not interchangeable with anything built with VC. You'll have make sure you have all of sdl2-mixer's dependencies in their VC form.

I've found [Dependency Walker](https://www.dependencywalker.com/) to be helpful. When I used it to examine flare.exe, the dependencies I was interested in appeared at the bottom of the list (the rest being Windows stuff). That might help you find what's missing.

**Comment by TanisTheRed** [comment]
Ok I finally got it to work.  I traced back to these sets of files that if you copy them over the other files in your folder with the exe for VC projects (debug, release, etc...) the sound works.

http://www.libsdl.org/projects/SDL_mixer/
SDL_mixer 2.0 - Simple DirectMedia Layer - Homepage<http://www.libsdl.org/projects/SDL_mixer/>
SDL_mixer 2.0 SDL_mixer 1.2 Authors: Sam Lantinga, Stephane Peter, and Ryan Gordon. Documentation: Available on this site.. Source: SDL2_mixer-2.0.4.zip SDL2_mixer-2 ...
www.libsdl.org


________________________________
