### ISSUE TITLE
Allow toggling touch control on GNU/Linux

### ISSUE THREAD

**Issue by McSinyx** [flareteam/flare-engine#1769]
Lately there's been new handheld devices running GNU/Linux natively, namely the [PinePhone](https://www.pine64.org/pinephone/) and the [Librem 5](https://puri.sm/products/librem-5/).  Even on the PinePhone's A64, performance-wise flare is still quite playable, so I'm suggesting exposing the touch control for Android/iOS for desktop builds as well, including (but not exclusive to) GNU/Linux.

**Comment by dorkster** [comment]
I support this idea. I recently got a 2-in-1 laptop that's running Linux, so I can test there.

On the flip side, I also think it would be wise to support non-touch input methods for mobile devices. Bluetooth is a thing, and people can connect their gamepads, keyboards, mice, etc to their phones.

**Comment by McSinyx** [comment]
Thank you @dorkster, this is awesome!
