### ISSUE TITLE
Stash with personalized tabs or multiple stashes

### ISSUE THREAD

**Issue by Sturwandan** [flareteam/flare-engine#1773]
While going through Empyrean campaign I wanted to keep every single item I found in the stash, just in case I would need them under a different character. It was possible in Alpha campaign, however Empyrean has much more items. Since stash interface already has tabs, why not to allow the player (or mods) to define the tabs?

For example I would like to have different stash tabs for weapons, armors, rings and other things. However, maybe it's already possible to do by writing a small mod which would be compatible with empyrean campaign?

Alternatively, perhaps items should be preserved if they are dropped onto the ground between reentering the level?

**Comment by dorkster** [comment]
I think it would be reasonable for mods to be able to define the stash's tabs. Each tab would have properties for the label text and whether or not the tab is shared.

**Comment by Sturwandan** [comment]
That would be great. It seems that empyrean campaign will need at least six stash tabs to have every single item, or even more if you want the items to be more neatly organized.
Do you think the tab can also have an icon with or instead of text? I don't think six tabs with full labels like "Weapons", "Helmets", "Chest" would fit in available space.

**Comment by Sturwandan** [comment]
Also another thought. Is it possible to have treasure chests replaced with small stashes (different for each chest)? Some other games have every treasure chest have multiple slots, just like player's inventory, with the content being persistent between reentering the area.
