### ISSUE TITLE
Improving the gamepad experience

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1783]
I've been working on this myself, but I wanted to open an issue here to add it to the 1.13 milestone. So I'll share my notes below. Some of these have been implemented, some are yet to be tackled.

- [x] Support arbitrary number of bindings per action instead of just 3
- [x] Migrate to SDL_GameController API
- [x] Prevent gamepad from selecting WidgetListBox items if selection is disabled (i.e. Character menu stats)
- [x] Remove actionbar bindings. Use standard movement/accept/cancel bindings.
  - [x] Add a binding to toggle between the actionbar and normal gameplay.
- [x] Separate binding for opening the pause menu
- [x] New bindings for switching active menu tabs (see #1745).
  - [x] Remove WidgetTabControl from all TabLists.
- [x] Maybe add a binding for activating the selected item? (kind of like right click)
- [x] When presented a menu, TabList should focus the first element.
  - [x] MenuTalker should select the first dialog option
- [x] More sensible default button mappings for gamepads.
  - Powers on shoulder buttons
- [x] WidgetListBox tooltips? Maybe activating the selected item can toggle the tooltip.
- [x] Possibly use right stick for some sort of aiming? Future idea: Maybe lock-on and target cycling.
- [x] Action remapping dialog shouldn't have an active tablist because of input conflicts
  - MenuConfirm should support multiple "confirm" options (use WidgetHorizontalList)
  - When remapping an action, the player should be presented with two options; "Assign" and "Clear"
  - Selecting "Assign" will lock the MenuConfirm tablist, which should eliminate the input conflicts
- [x] Context menus for MenuItemStorage and action bar slots?
  - Actions for: *Move/Reorder*, *Use/Activate*, *Drop/Clear*, *Buy/Sell/Stash*
  - Utilize new multiple-choice feature of MenuConfirm
- [x] Add binding for cycling loot tooltip modes
----

Progress can be followed on this branch: https://github.com/dorkster/flare-engine/tree/input_refactor

**Comment by WithinAmnesia** [comment]
Looking good :-)!
