### ISSUE TITLE
Intro loops on Android

### ISSUE THREAD

**Issue by johndh** [flareteam/flare-engine#1787]
This is my first time trying to play Flare on Android. After installing the APK and the data, I start a new character, and the intro plays. After clicking through the screens, I get a brief "loading" bar, and the intro starts over again. This continues forever, as far as I can tell.

**Comment by dorkster** [comment]
I believe this is the same bug that was reported a while back in the blog comments. There were some issues with both read and write permissions on Android 10 and up. Did you try the version 1.12.12 APK from the wiki page? It should have [this fix](https://github.com/flareteam/flare-engine/commit/6bd78b3a868cd857a656caec8d8c95e1ec6bc8e3) included.

**Comment by johndh** [comment]
Fixed in 1.12.12
