### ISSUE TITLE
Android: "Press (Right Mouse) to use"

### ISSUE THREAD

**Issue by johndh** [flareteam/flare-engine#1788]
The mortar and pestle has a tooltip that doesn't make sense on a touch screen, or at least isn't readily obvious.

**Comment by dorkster** [comment]
Agreed. The current way to use an item on mobile is to "select" it twice, effectively a double-tap. I don't think this is very intuitive. I've been considering adding a context menu for items with the following possible options:

- Move/Reorder
- Use/Activate
- Drop
- Stash/Buy/Sell

This would also help all control schemes that use a subset of the available inputs (e.g. mouse-only, gamepad, etc). So this would probably tie into the list of improvements for #1783.
