### ISSUE TITLE
Flare Engine stops rendering character/enemy sprites past ~1,000 yet no FPS drop at 1,000; increase sprite limit to 10,000-100,000?

### ISSUE THREAD

**Issue by WithinAmesia** [flareteam/flare-engine#1790]
@dorkster I ran a stress of a 1000x1000 map with 1,709-6,836 ~4,272.5 skeletons + the player and the sprites did not load yet the FPS was fine.
Then I ran another stress of a 1000x1000 map with ~3,000 skeletons + the player and the sprites did not load yet the FPS was fine.
Then I ran another stress of a 1000x1000 map with ~2,000 skeletons + the player and the sprites did not load yet the FPS was fine.
Then I ran another stress of a 1000x1000 map with ~1,000 skeletons + the player and the sprites **_did_** load and the FPS was still fine.

Is there an stack over flow or some kind of internal sprite limit on the Flare engine (I spammed out ~4,000+ of the same skeleton on the same 1000x1000 tile map and it did not load / render in)? If there is an internal sprite limit on the Flare engine per map / area can this become unlimited / at least ~10,000 or 100,000 (for particles and ~summon spam)? If at maximum a 1000x1000 tile area has 1 enemy every ~100 tiles (~squared) that could be 10,000 enemies per map. Now this is the upper end of a stress test but still I want to push my best PC to its limits and see if a 1000x1000 tile map can also have 2,000 to 10,000 enemies and see how I can build my super dungeon levels / my ~overworld levels in general.

I am curious as to why the sprite stop loading at ~1,000+ and if this can be fixed to enable large scale maps in Flare.

**Comment by dorkster** [comment]
So I believe this bug actually has nothing to do with the number of enemies on the map. I was able to reproduce it by placing a single skeleton at the bottom corner of a 1000x1000 map, and my character disappeared when near the middle of the map.

I'm 99% sure the bug has to do with the way we prioritize sprites during rendering. Part of determining the priority is looking at which tile the sprite is on. The catch here was that we were assuming a maximum map size of 256x256. so the bit shifting we were doing did not leave enough room, causing the priority variable to overflow.

Please try this Windows build, which includes [the commit](https://github.com/flareteam/flare-engine/commit/ebf1fd75737b55926eb195d4add778f510472dc5) that should fix this: https://drive.google.com/file/d/1WiiWG5We9gZGi_Z4aWWM_OAfu_sHAjhC/view?usp=sharing

**Comment by WithinAmnesia** [comment]
Okay I will test it out after this post. (In the first post above) I tested in the top corner and deleted mobs from the bottom (for ~3,000) then the left (for ~1,000) and the the right (for ~1,000). By coincidence I ended up with mobs / sprites being tested before in the top corner.

**Comment by WithinAmnesia** [comment]
@dorkster We got success!!! https://www.deviantart.com/withinamnesia/art/1000x1000-Map-4-273-Enemy-Stress-Test-Success-898518659
Not even a bit of lag! Solid FPS from top to bottom. No 'ghost skeletons'. Just great. I pepper the entire are with skeleton spawns and damn they are everywhere XD. thank you so much :-D!
