### ISSUE TITLE
Right-clicking on scrolls in inventory doesn't perform the "cast" animation

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1793]

**Comment by WithinAmnesia** [comment]
How will this be handled? Will items have the option to trigger an arbitrary animation like swing, cast, fall etc on use?

**Comment by dorkster** [comment]
The cast animation is set by the power. I noticed this bug when using the scrolls in the Empyrean campaign. If you use them from the action bar, the animation plays (the correct behavior). But no animation plays if you use them directly from the inventory.
