### ISSUE TITLE
event.requires_item unsure how to make multiple of the same required item work. 

### ISSUE THREAD

**Issue by WithinAmnesia** [flareteam/flare-engine#1796]
@dorkster Can you please help myself?

My Objective:
Find how to have "requires_item=" work in Flare with an arbitrarily amount of multiples of the same item id; such as requires item id 3097 x 3.

My Observation:
event.requires_item is acting odd to my tests to require multiples of the same item in order to 'gate' and even in this case a crafting button in a book.

So far I have this button in a test Blacksmithing book menu; and the requires item id '3097 x 3' I am failing to get working, I did get the requires X currency to work for the button. Yet I got the crafting script to work.
"# Craft Dagger Test
[button]
button_pos=248,280
text=Forge Copper Off-Hand Dagger.
requires_currency=100
requires_item=3097;3097;3079
script=scripts/AGABAL/Crafting/Blacksmithing/Crafting_Test_Copper_Off-Hand_Dagger.txt"

[Semi-relevant: I also moved the regular Alchemy "Craft" button to button_pos=248,248 for originally I had the Blacksmith crafting button at 312 but it fell off the book menu; so I shifted both buttons up by 32.]

My Issue:
I cannot figure out hot to get this to work where it requires item id 3097 x 3 (a.k.a. Copper Ingot x 3) to work where 3097 x 3 makes the craft button work but instead only 3097 x 1 is needed.

My Failed Attempts:
requires_item=3097,3 (needs both item id 3097 and item id 3; fail). Strange because reward_item=3097,3 works yet remove_item=3097,3 does not. I read this "event.reward_item | (list(item_id) | Reward hero with a specified item. Quantity can be specified by appending " Q" to the item_id, where Q is an integer. To maintain backwards compatibility, the quantity must be defined for at least the first item in the list in order to use this syntax." and it looks like 2 ~'rule sets' are being used.

I read this line "event.requires_item | list(item_id) | Event requires specific item (not equipped). Quantity can be specified by appending " Q" to the item_id, where Q is an integer." and the top part of the Attribute Reference (https://github.com/flareteam/flare-engine/wiki/Attribute-Reference )
I tried some failed attempts:

This fails as well:
requires_item=3097
requires_item=3097
requires_item=3097

requires_item=3097 3   [fails]
requires_item=3097" 3"   [fails]
requires_item=3097," 3"   [fails]
requires_item=3097"3"   [fails]
requires_item=3097,"3"   [fails]
requires_item=3097( 3)   [fails]
requires_item=3097(3)   [fails]
requires_item=3097,( 3)   [fails]
requires_item=3097,(3)   [fails]
requires_item=3097;3097;3079   [fails]
requires_item=3097,3097,3079   [fails]
requires_item=3097;( 3)   [fails]
requires_item=3097;(3)   [fails]

My Partial Success:
[This works]
Script "Crafting_Test_Copper_Off-Hand_Dagger.txt":
[event]
remove_currency=100
remove_item=3097;3097;3097
reward_item=3071

Also this works for the script (earlier version):
[event]
remove_currency=100
remove_item=3097
remove_item=3097
remove_item=3097
reward_item=3071

My Conclusion:
I am not super amazing at scripting in Flare; yet. Although with some help from my friends I might become better; I hope at least enough to get the expanded crafting system to work XD.

**Comment by dorkster** [comment]
A colon is used to delimit quantity. I guess it got stripped out in the doc generation script. Example:

```
requires_item=3097:3
```

**Comment by WithinAmnesia** [comment]
It works now!

**Comment by Danimal696** [comment]
It´s nice you got it to work, but the problem is how bloated things can get if you overly use this, think using this in 100 items, you need to use it sparingly or you will go crazy. Could you post a pic of how it ended up looking?
