### ISSUE TITLE
Intro plays multiple times game doesnt start

### ISSUE THREAD

**Issue by Nerlif** [flareteam/flare-engine#1800]
When I try to start the game and choose my portrait and name, the game starts with a legend of how I was exiled, well i cant pass of this intro, it repeats that intro and dont let me play, am I doing something wrong?

**Comment by dorkster** [comment]
Are you playing the Android version? If so, this sounds like a duplicate of https://github.com/flareteam/flare-engine/issues/1787

**Comment by Nerlif** [comment]
Yes, I do let me try 12.12

**Comment by Nerlif** [comment]
It worked ty so much
