### ISSUE TITLE
Scaling XP based on the difference of player/enemy level

### ISSUE THREAD

**Issue by WithinAmnesia** [flareteam/flare-engine#1807]
"Scaling XP based on the difference of player/enemy level is a reasonable idea." + [Question: "Can this feature make it into 1.14 without too much hassle?"] Answer: "I don't think the implementation would be too complicated, so I'll go ahead and say "yes" at the moment." From: https://github.com/flareteam/flare-game/discussions/890#discussioncomment-2020627 + https://github.com/flareteam/flare-engine/issues/1806#issuecomment-1012643094 .

**Comment by WithinAmnesia** [comment]
@dorkster How hard / complex is it to implement Scaling XP based on the difference of player/enemy level? I am not aware of the possible ~'gremlins' that could be faced with this implementing this feature in 1.14. Yet I can see a lot of benefits if it was implemented.

A current immediate benefit could be more powerful / efficient work flow for making wide arrays of creatures with XP scaling. As with using only one version of an enemy creature instead of ~3 (or more) that are using clunky pre-baked experience reward differences and spawn using fixed level ratios. As like 100% XP for version 1 of an enemy that spawns from player levels 1-10. Then a version 2 with 50% exp version spawns from levels 11-20. Then a version 3 with 10% experience that spawn from levels 21+. All of this is clunky to make, it works, but it has issues with accurate bug testing and clutters Tiled.exe Flare maps for every enemy has 3+ versions. Also there are weird XP drop off 'cliffs' with 100% XP -> 50% XP over the difference of one level for some enemies verses the player level (e.g. as the above example with enemy level 10 100% XP verses enemy level 11 50% XP). If XP scaling was implemented this could be smooth XP reward transition instead of a clunky and jagged feeling system of pre-baked XP-scaling that works, but is inefficient and with run-away complexity and difficulty in with accurate bug testing large amounts of enemy creatures throughout a game.

As it currently stands I use a clunky pre-baked XP scaling with 3 versions that are using player level to trigger hopefully one of the appropriate versions to spawn (like in the above example). This works currently but it is 5.5/10 or a around a ~'D' in grade letters as it feels to myself at least. Also it could be nightmare to test for everything is done by hand and there is a risk of getting the level transition wrong and nothing spawns (a gap) or more than one type spawn (an over lap). With XP scaling this could be automatic and more efficient to build a game content with; especially larger areas and or a game with lots of enemies throughout. I am just unsure as to how complex this is to implement for 1.14 and I wonder if there are too many ~'gremlins' surrounding this potential feature or if it is on the more reasonable end of the spectrum?

**Comment by dorkster** [comment]
This should actually be really simple. I math I described [here](https://github.com/flareteam/flare-engine/issues/1806#issuecomment-1013533073) should do the trick. There's no difficulty setting (F) yet, so that could just be hard-coded as 1 for now.

This feature would pair well with #1813, so I'll add this to the 1.14 task list.

**Comment by dorkster** [comment]
Ok, I did some more thinking about this and the approach in my first comment is irrelevant here. It could provide some additional scaling if the player levels up after the enemies are spawned, but we need to scale the base XP first. The XP should scale here even if the player and enemy levels are the same. I think what we need is something like this:

```
# this would be in an enemy statblock file
xp_scaled=<function>,<parameter>
```
There would be two possible functions: `linear` and `exponential` (we essentially use the latter in flare-game)
Both of these would take a single parameter (a float), which we'll call X here

```
Linear XP = level * X
Exponential XP = X ^ level
```

**Comment by WithinAmnesia** [comment]
I think I should have put an XP table in in my request to better communicate on my end XD.

This is what I currently use to manually scale experience rewards of enemy level verses player level by hand:

(Game / creature / player level range 1 to 100).

Current pre-baked system I use to scale enemies:
0+ to -10 creature levels verses player level = 100% experience reward of 1,000 XP = 1,000 XP

-11 to -20 creature levels verses player level = 50% experience reward of 1,000 XP = 500 XP

-21+ creature levels verses player level = 10% experience reward of 1,000 XP = 10 XP

Partially inspired from / similar in style to: https://www.reddit.com/r/classicwow/comments/abqyrc/exp_formula_for_all_lvls/


@dorkster Could these ideas be possible?

This is close in principle to what I would like to use to scale experience rewards of enemy level verses player level via a table:

0+ to -10 creature levels verses player level = 100% experience reward of 1,000 XP = 1,000 XP

-11 creature levels verses player level = 95% experience reward of 1,000 XP = 950 XP
-12 creature levels verses player level = 90% experience reward of 1,000 XP = 900 XP
-13 creature levels verses player level = 85% experience reward of 1,000 XP = 850 XP
-14 creature levels verses player level = 80% experience reward of 1,000 XP = 800 XP
-15 creature levels verses player level = 75% experience reward of 1,000 XP = 750 XP
-16 creature levels verses player level = 70% experience reward of 1,000 XP = 700 XP
-17 creature levels verses player level = 65% experience reward of 1,000 XP = 650 XP
-18 creature levels verses player level = 60% experience reward of 1,000 XP = 600 XP
-19 creature levels verses player level = 55% experience reward of 1,000 XP = 550 XP
-20 creature levels verses player level = 50 % experience reward of 1,000 XP = 500 XP

-21 creature levels verses player level = 45% experience reward of 1,000 XP = 450 XP
-22 creature levels verses player level = 40% experience reward of 1,000 XP = 400 XP
-23 creature levels verses player level = 35% experience reward of 1,000 XP = 350 XP
-24 creature levels verses player level = 30% experience reward of 1,000 XP = 300 XP
-25 creature levels verses player level = 25% experience reward of 1,000 XP = 250 XP

-26 creature levels verses player level = 22.5% experience reward of 1,000 XP = 225 XP
-27 creature levels verses player level = 20% experience reward of 1,000 XP = 200 XP
-28 creature levels verses player level = 17.5% experience reward of 1,000 XP = 175 XP
-29 creature levels verses player level = 15% experience reward of 1,000 XP = 150 XP
-30 creature levels verses player level = 12.5% experience reward of 1,000 XP = 125 XP

-31+ creature levels verses player level = 10% experience reward of 1,000 XP = 100 XP

This style of all enemies having the same base experience reward amount regardless of enemy level (of say ~1,000 experience) enables a precise calculation of player experience tables verses time spent killing enemies. So as to accurately equate an average amount of time spent by the player in order to earn the next level.

This then requires level scaling like the above in order to implement.

As like in the monster stat sheet having values for arbitrary base experience rewards of X and having that multiplied by player level of X. Where a scaling XP table table of sorts could be used almost like a loot table but with if player level is either =X or >=X or <=X could work as well.


A level 27 Skeleton Mage in the stat sheet could have a customizable / arbitrary (and hopefully standardized copy and paste to save work for making many enemies) level scaling XP reward table like this is if only manual values like =X or >=X or <=X could could be used to scale creature XP rewards in the enemy stat sheet:


~'Skeleton Mage' (level 27)


player level >=37 (same as 0+ to -10 creature levels verses player level) = 100% experience reward of 1,000 XP = 1,000 XP

player level =38 = 95% experience reward of 1,000 XP = 950 XP
player level =39 = 90% experience reward of 1,000 XP = 900 XP
player level =40 = 85% experience reward of 1,000 XP = 850 XP
player level =41 = 80% experience reward of 1,000 XP = 800 XP
player level =42 = 75% experience reward of 1,000 XP = 750 XP
player level =43 = 70% experience reward of 1,000 XP = 700 XP
player level =44 = 65% experience reward of 1,000 XP = 650 XP
player level =45 = 60% experience reward of 1,000 XP = 600 XP
player level =46 = 55% experience reward of 1,000 XP = 550 XP
player level =47 = 50 % experience reward of 1,000 XP = 500 XP

player level =48 = 45% experience reward of 1,000 XP = 450 XP
player level =49 = 40% experience reward of 1,000 XP = 400 XP
player level =50 = 35% experience reward of 1,000 XP = 350 XP
player level =51 = 30% experience reward of 1,000 XP = 300 XP
player level =52 = 25% experience reward of 1,000 XP = 250 XP

player level =53 = 22.5% experience reward of 1,000 XP = 225 XP
player level =54 = 20% experience reward of 1,000 XP = 200 XP
player level =55 = 17.5% experience reward of 1,000 XP = 175 XP
player level =56 = 15% experience reward of 1,000 XP = 150 XP
player level =57 = 12.5% experience reward of 1,000 XP = 125 XP

player level <=58 = 10% experience reward of 1,000 XP = 100 XP

Or possibly just have a link in the enemy statblock to a xp scaling table .txt file like:
xp_scaling_table = xp_scaling_level_27.txt (in that xp scaling table could be something like the above example with the level level 27 manually scaled xp reward brackets made to have diminishing returns with higher player levels verses the monster level).


Is it possible to implement this kind of level scaling on the enemy stat sheet / enemy statblock file with some kind of these three values working to scale enemy experience rewards verses player level with using the these values of:
a.) Base experience reward = X (e.g. 1000)
b.) If Player level =X (if player level equal to X) then multiple base experience reward by X
c.) If Player level >=X (if player level greater than or equal to X) then multiple base experience reward by X
d.) If Player level <=X (if player level less than or equal to X) then multiple base experience reward by X

I am not sure how these would look like as written compact values perhaps something like this?:

a.) experience = X
b.) if_player_level = X (then) = experience (possibly of X) * X 
c.) if_player_level >= X (then) = experience (possibly of X) * X
d.) if_player_level <= X (then) = experience (possibly of X) * X

Or like this?:

Level 27 Skeleton Mage
a.) e.g. if_player_level <= 37 = experience 1000 * 1   //(100% *a)
b.) e.g. if_player_level = 47 = experience 1000 * 0.5   //(50% *b)
c.) e.g. if_player_level >= 58 = experience 1000 * 0.1   //(10% *c)

*a (if player level is greater than or equal to 37, then arbitrary experience of 1000 x 100% = 1000 experience reward)
*b (if player level is equal to 47, then arbitrary experience of 1000 x 50% = 500 experience reward)
*c (if player level is less than or equal to 58, then arbitrary experience of 1000 x 10% = 100 experience reward)


Or possibly this?

If this is in the enemy statblock file:
xp_scaled=<function>,<parameter>

Could this work with the above xp scaling table approach with adding an arbitrary XP scaling table .txt file as a sort of a function?

[level 27 enemy statblock file]
xp_scaled=<xp_scaling_level_27.txt>,<1000>

Would that make any sense?

---------------

What would be a possible feasible solution for this style of table of level scaling enemy experience rewards?

**Comment by dorkster** [comment]
Yeah, I was confusing myself here. There's two types of XP scaling being described here, "absolute" and "relative". And I think we should have both.

I like your approach of using a table for this, since then the modder can use whatever "function" they want to create their XP ramp. An XP scaling file would have two sections, one for each type of scaling. Modders would be able to use one, both, or neither. The sections would consist of level/multiplier pairs.

Here's how flare-game's current XP ramp for non-boss enemies would look:

```
# All enemies would have xp=2
[absolute]
level=1,1
level=2,2
level=3,4
level=4,8
level=5,16
level=6,32
level=7,64
level=8,128
level=9,256
level=10,512
level=11,1024
level=12,2048
level=13,4096
level=14,8192
level=15,16384
level=16,32768
# anything higher than level 16 would just use level 16's multiplier
```

And since this would be a separate file that could be referenced in a statblock definition, bosses could use their own table.

But anyway, here's how your relative table would look:

```
[relative]
level=-10,1
level=-11,0.95
level=-12,0.9
level=-13,0.85
level=-14,0.8
level=-15,0.75
level=-16,0.7
level=-17,0.65
level=-18,0.6
level=-19,0.55
level=-20,0.5
level=-21,0.45
level=-22,0.4
level=-23,0.35
level=-24,0.3
level=-25,0.25
level=-26,0.225
level=-27,0.2
level=-28,0.175
level=-29,0.15
level=-30,0.125
level=-31,0.1
```

**Comment by WithinAmnesia** [comment]
Okay, that reply is a lot more elegant than my messy all over the place loose set of thoughts XD.

So with what you said above. In that line of thought, could it be possible to implement what I said above with the ~'relative player level' scaling xp tables?

1.)* I suppose that like what you posted under [relative] could be absolute experience values be for example 1,000 experience reward for all enemy levels like experience = 1000 / xp=1000

2.)* Then have relative xp scaling like in your example under [relative].

If 1.)* and 2.)* were put together that should in theory make a working system where the experience reward from enemies is scaled relative to player level (as described in your above [relative] table example). Then in effect being able for a game developer to create a relative level experience scaling system as what I described above your reply. So as to hopefully be able to implement in a Flare video game that table style of relative level experience scaling system.

As found here https://github.com/flareteam/flare-engine/issues/1807#issuecomment-1049728664 with that brainstorming collection / list of level brackets and experience multipliers per relative player level verses enemy level and other loose related thoughts of what you described above. Yet you did so in your reply in a fashion that is much more compact and eloquent than my first attempt at describing a table based relative level experience scaling system XP.

So I think with what you said that if those [absolute] and [relative] experience table / level scaling experience reward systems were implemented as you described them above. It should be possible to implement my style of ~'1000 base experience reward for all monsters that is modified / scaled relative to player level verses enemy level with experience multiplied from values found on a table'; that kind experience scaling system should be possible, hopefully?

**Comment by WithinAmnesia** [comment]
@dorkster How does one set this up?

https://github.com/flareteam/flare-engine/wiki/Attribute-Reference#xpscaling
"XPScaling

Description of enemies/xp_scaling/"

Does one make a 'xp_scaling' folder within  the enemy folder and the make a .txt file called something(?) and use something kinda like this?
[relative]
level=-10,1
level=-11,0.95
level=-12,0.9
level=-13,0.85
level=-14,0.8
level=-15,0.75
level=-16,0.7
level=-17,0.65
level=-18,0.6
level=-19,0.55
level=-20,0.5
level=-21,0.45
level=-22,0.4
level=-23,0.35
level=-24,0.3
level=-25,0.25
level=-26,0.225
level=-27,0.2
level=-28,0.175
level=-29,0.15
level=-30,0.125
level=-31,0.1

Or does that list go on each enemy in their .txt file or?

Like what would be an example of all of this working and set up?

**Comment by dorkster** [comment]
Yes, you would create a separate text file for each XP scaling table. You would then use `xp_scaling=<filename of XP scaling table>` in the enemy definition file. So you can put the XP scaling table files anywhere, but I recommend `enemies/xp_scaling/`.

For example:

```
# enemies/xp_scaling/my_table.txt
[relative]
level=-10,1
level=-11,0.95
level=-12,0.9
# etc...
```

```
# enemies/skeleton.txt
xp_scaling=enemies/xp_scaling/my_table.txt
```
