### ISSUE TITLE
Arbitrary definition of main attributes (e.g ~6 attributes to invest into, up from 4 attributes)

### ISSUE THREAD

**Issue by WithinAmnesia** [flareteam/flare-engine#1809]
I am hoping to have 6 main attributes for the player character to invest into when they level up (Strength, Agility, Constitution, Perception, Intelligence, Charisma).

I like the current way of how each main attribute can be tweaked to add or remove / change what character statistics they modify; that part is very useful.

I am hoping to have a way to add an arbitrary amount (but in my case 6 can do) of main attributes (with arbitrary names) that can be invested into / increased upon level up. Also that are hopefully working with items / itemization and abilities / spells / effects etc. and other relevant areas of game mechanics that drive the core gameplay experience.

(Also if not already working): To also have the names of the possible main attributes be arbitrary.
So that the creative community can be free to have an array of possible options for making their video games. Also to be able to give the main attributes arbitrary / appropriate possible themes for each video game setting. The potential reward for arbitrary main attributes with arbitrary names could be massive to empower the creative community, and to help make all kinds of video games created with the Flare Engine.

Here is a Gist of my 4 Main Attribute stats.txt from my prototype build (taken from Flare Version 1.13 R.C.2)
https://gist.github.com/WithinAmnesia/7024745858f475d36e0c441e7d7951d2

Also I quickly looked around GitHub for a similar Flare Engine issue, but I came up short. So I decided to post this to address a long running desire I have had to be able to add more options for main attributes when making video games with the Flare Engine.

Also what parts are needed for something like this to work? Does the menu have special details that affect this particular area? How would itemization be affected if the main attributes had arbitrary names? Is there a hard limit to how many main attributes could be added (within reason / screen real estate)?

What important details should be discussed for something like this? Also what is the difficulty / complexity to implement something of this nature for the Flare Engine?

Is it possible (within reason) for the Flare Engine to be able to support arbitrary main attributes that can also have arbitrary names?

**Comment by dorkster** [comment]
You can define the main attributes in [engine/primary_stats.txt](https://github.com/flareteam/flare-engine/blob/master/mods/default/engine/primary_stats.txt). You can then use whatever is entered as the `id` to reference a stat in places like `engine/stats.txt`

**Comment by WithinAmnesia** [comment]
I got it working. Also I tested that a statistic for example hp can be modified by multiple primary attributes. Take care everyone.
![Six Primary Attributes, All Attributes Working!](https://user-images.githubusercontent.com/86871191/151723264-cd642ae0-f32a-49f7-811d-e1772bc6bf15.png)
