### ISSUE TITLE
Random item generation

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1815]
These are some of my current thoughts on implementing this:

- Instead of storing the whole item definition, just store the seed. This would be much less of a leap for our current save file format: Just have a list of seeds like we have a list of IDs and quantities.
  - **EDIT: We'll also have to store the item level.** As to not add another array to the save file, perhaps it should be written together with the seed and delimited by a colon. Example: `carried_seeds=<level>:<seed>,...`
- The ItemStack class would store the seed so the item can keep its properties as it's moved around.
  - Maybe there'd need to be a cache of the seeded item's properties, but I would first try an on-the-fly approach and generate the item as we need it.
- Items would be able to specify a rule file to use for generating new items. If a rule is defined, the base item ID and seed get passed to the generator.
- Rule files would contain:
  - The min/max level difference from either the item's base level or the player's level (or enemy level?)
  - Possible item qualities, their chance of overriding the base quality, and the min/max number of bonuses
  - A list of possible bonuses with their min/max value per level
  - Min/max addition buy/sell prices
  - Probably other things I'm forgetting
- Retain the base item's name to keep translation simple. Maybe add an indication that it's a generated item, like an asterisk or something.

**Comment by WithinAmnesia** [comment]
Can you give some examples of how this would play out?

**Comment by WithinAmnesia** [comment]
Also is this optional like it can go along side what already exists; like an optional feature?

**Comment by dorkster** [comment]
It would *have* to be optional, since there are plenty of items that don't need the random treatment. Basically, if an item lacked a reference to a randomizer rule file, the item would work exactly like the existing items. The seed and item levels will be saved as zeroes to indicate this.

Here's a prototype of what the rule file could look like:
```
# The level section will only be used when generating a new item. 
[level]
# This line will tell the generator where to source the starting level from.
# Possible values would be 'base' and 'hero'.
# The former being the base item's level, the latter being the player's level.
level_src=hero

# This defines the min/max level offset based on the source level
# In this example, let's say the player's level is 5.
# The following line means that the generated item will be between levels 3 and 8 inclusive.
level_range=-2,3

# The quality section lists chances for the item to be of a certain quality.
# It also defines the min/max number of bonuses for a given quality.
# The format is: quality=<id>,<chance>,<min_bonus>,<max_bonus>
# The chances work like loot drop chances. If a random roll is less than or equal to the chance,
# the quality will added to the pool of qualities to pick from.
# Let's say that the chance roll is 5. In the example below, the item will either be 'high' or
# 'epic' quality.
[quality]
quality=high,100,2,3
quality=epic,5,3,4
quality=rare,0.5,4,5

# The bonus section describes the possible bonuses that the random item can have.
# The format is: bonus=<stat>,<min_value>,<max_value>
# Items will only be able to have one bonus per stat.
# So in this example, the item will max out at 3 bonuses (crit, hp, fire_resist),
# even if its quality allows for more.
[bonus]
# Using the 'bonus' property, it's possible to have a bonus that's not affected by item level.
# So no matter what level the item is, it will gain a 2-5% critical hit chance if this bonus is selected
bonus=crit,2,5

# And this would give a 25 HP bonus
# Note that this will get combined with the bonus_per_level line below because they both use the 'hp' stat
bonus=hp,25,25

# On the other hand, 'bonus_per_level' will scale with the item level.
# Let's say our generated item level is 4.
# That would mean our potential bonuses are 225-325 HP and 8-12% Fire Resistance
bonus_per_level=hp,50,75
bonus_per_level=fire_resist,2,3
```

**Comment by dorkster** [comment]
>Meaning that a 3 bonus item can be an upper end "High(2,3)" or low end "Epic(3,4)"?

Yes. The item would be able to have *up to* the number of defined bonuses, but not more. So in our example, it would be impossible to have an Epic item with 4 bonuses because there just aren't that many to pull from.

>Next would be if "bonus" would be universally chosen from a list of all possible bonuses or restricted by a user defined list of bonuses per item?

The latter. We'd want to have the ability to restrict certain bonus types to certain item types. For example, weapons might only have damage bonuses, while armor would have absorption and elemental resist bonuses.

>Another thing you hypothesized would be socketable items, that opens the way to have gems of different qualities to drop and a way for the player to fuse them into higher quality with something like a Horadric cube.

I mainly brought that up to demonstrate what could be accomplished by changing the way we format inventory/stash item storage in save files. Such a change would have been necessary if we decided to save the entire item definition for generated items. The item generation approach I detailed here doesn't require this change and would remain fully compatible with existing saves. However, it may still be worth making the shift to prepare for things like socketed items. I imagine it would look something like this:

```
[item_storage]
slot_index=...
item_id=...
quantity=...
random_seed=...
random_level=...
```

**Comment by WithinAmnesia** [comment]
'Enchant-able' / socket-able items? Or will Flare have to use a sort of system where a game developer has to just have a sort of quest / crafting system with an exhaustive pre-defined list of all possible combinations behind the scenes (Like tens of thousands of possible combination entries)?

**Comment by WithinAmnesia** [comment]
Didn't D3 (I know PoE does) have ~'crafts-people' who a player can ~'unlock' / get a ~'house' / base and then have the crafts people 'level up' / get better / get more recipes / build / get a bigger 'forge' / crafting world object-thing and that effectively acts like leveling up a crafting skill but it is not directly the player. Like in history a Castle would have a blacksmith building inside the walls and a kitchen and other profession buildings and the Lord did not directly craft anything (because they go to war / run the show / have other more exciting things / responsibilities to do; _in theory_) but could set up the infrastructure / commission work. In Baldur's Gate this is done with the blacksmith in a town when a player can get a special bug chitin / body parts and then work out a deal with the smith to craft armour for a fee and a time delay: https://baldursgate.fandom.com/wiki/Taerom_Fuiruim

**Comment by WithinAmnesia** [comment]
I guess enchantments could just be reskinned / rebranded gems like in Diablo II. Same thing in the end but reusing mechanics and could act to steam-line / not get too overly complicated for no good reason. Also I think Harvest Moon and Stardew Valley don't have a farming skill but have like non-changing game world then a small 'player property' that can have crops and and game objects removed / altered. I don;t thin k having a billion skills is necessary in some games yet having the spirit of professions ~'_would be nice_' (yet feature creep is not nice lol XD) but like Baldur's Gate the player does not need to be a 'blacksmith' to feel like they are progressing in a sort of blacksmithing way / to make items from their adventures.

**Comment by WithinAmnesia** [comment]
I think the Diablos have a gambling vendors that kind of act like random item generators at the cost of in game resources. Almost like crafting. I guess something similar could be made with this random item proprieties generation system where raw resources go in / get traded (via a dialog / repeatable quest option?) and then a random property (or semi-random range of properties) item is provided to the player / is 'generated'. Something like that or even a 'loot box' item that contains a pre-defined loot table could work like that took I suppose but with less moving parts / complexity / range of options.

**Comment by WithinAmnesia** [comment]
So @dorkster Flare and ~'socket-able' items? Is this even do-able / worth it? Or is this effectively kind of feature-creep?

I suppose if it happened (somehow) that it could be reposed for item augmentations (like ~'enhancements' ['Fire Brand' / 'Fire Rune' +2 ~fire damage _or something_] ). Would this even be possible or it is kind of just not really do-able?

Are socket-able items sort of kind of related to your idea of Random Item Generation property storing mechanics / ~'new ways of storing extra random item property values' or are these things kind of separate?

**Comment by dorkster** [comment]
Adding sockets to items was simply an example of something we **could** do if the aforementioned changes are made to the way item storage is handled in save files. I don't want to write it off just yet, but I'd say it's a bit on the "feature creep" side as it stands.

It also has nothing to do with random item generation, so it's a topic for another time/thread. Let's keep this discussion focused on just random item generation.

**Comment by WithinAmnesia** [comment]
https://classic.wowhead.com/item=15221/holy-war-sword So is this more of the fate that we should be talking about for Flare? Random Stat Value Items like this? Or like what Diablo II does with almost every magical/rare/set/crafted/unique/runeward item?

**Comment by dorkster** [comment]
Yes, that's a good example of the type of item this system would be able to create. The only exception being there'd be no prefix/suffix added to the item name so we can keep localization simple.

**Comment by WithinAmnesia** [comment]
@dorkster Can items retroactively gain more attributes / stats (random or fixed values +1 X or +1-3 X) with this system / idea? Or is a case where every stat generated at item generation / creation?

**Comment by Danimal696** [comment]
A way to empower existing items would be pretty cool, like upgrading to player level or adding more bonuses

**Comment by dorkster** [comment]
I think it would be best to start by keeping it simple and not allow item modification beyond the initial generation step. Such an augmentation system could work in theory, but I'm not sure it's something I'd want to add to Flare.

**Comment by ate088** [comment]
Just read this discussion and wish to chime in with my opinion on socket-able items: if the issue is not one of scope, I don't think there is any reason not to include it. It would make the engine more popular with players and modders. 

One thing I have learned from releasing my own Diablo-like game is that players tend not to be happy if something that is expected in a certain genre of game is not there, despite my own personal vision as the dev for whether it 'fits' or not.

Of course, this is just my opinion so take it as you will, but the decision to allow for randomized stats on items definitely brings it closer to being seen as a 'proper' Diablo-like. Might open a can of worms however, some people want to use the engine to make games that are of different genres.

**Comment by dorkster** [comment]
# Progress update

#1871 is finished, but I need to test it more thoroughly to make sure there's no invalid memory accesses. But in it's current state, it was functional enough to start working on random item generation. I'm happy to say that it's all working pretty well. Let's take a look at my testing configuration:

### items/items.txt
```
[item]
id=2003
name=Mysterious Cloth Shirt
INCLUDE items/base/armor/cloth/chest.txt
level=1
price=base:75,item_level:75
randomizer_def=items/random/test.txt
```

### items/random/test.txt
```
[option]
chance=100
quality=high
bonus_count=1,1
level_src=base
level_range=1,1

[option]
chance=5
quality=epic
bonus_count=1,2
level_src=base
level_range=2,2

[option]
chance=0.5
quality=rare
bonus_count=2,2
level_src=base
level_range=3,3

[bonuses]
bonus=hp,item_level:1:25
bonus=mp,item_level:1:3
bonus=hp_regen,item_level:1:25
bonus=mp_regen,item_level:1:3
bonus=accuracy,base:0:5,item_level:1
bonus=avoidance,base:0:5,item_level:1
bonus=crit,base:0:5,item_level:1
bonus=absorb_max,base:0:5,item_level:1
bonus=poise,base:0:5,item_level:1
bonus=xp_gain,base:0:5,item_level:1
bonus=currency_find,base:0:5,item_level:1:2
bonus=item_find,base:0:5,item_level:5
bonus=fire_resist,base:8:10,item_level:1:2
bonus=ice_resist,base:8:10,item_level:1:2
bonus=lightning_resist,base:8:10,item_level:1:2
bonus=dark_resist,base:8:10,item_level:1:2
bonus_power_level=37,base:1
bonus_power_level=111,base:1
bonus_power_level=152,base:1
```

## Generate/randomize
So how does it work? When item `2003` is dropped, we copy the item to a new ID above a certain threshold (currently hard-coded to 3000). The new item is what we'll call an "extended item". Once allocated, we pick an `option` that can set the item's quality, level, and number of bonuses.

The individual bonuses are rolled after that. It's important to note that the syntax for level-scaled values has been extended. Instead of a single value, there can now be 3 values, delimited by colons. All 3 together can define a range that the randomizer can use to pick a final value. The first value is the minimum and the second is the maximum. The third value is the "step", which defaults to 1. Say we want to generate a value between 1 and 5. We'd probably want the set of possible values to be `(1, 2, 3, 4, 5)` and not end up with something like 3.1459.

## Storage

Random items get written to `extended_items.txt` under the game's save prefix. IDs will be consistent across save files from the same game, so shared stash usage is possible. Here's an example of the item from the screenshot shown below:

```
[item]
id=3014,2003
level=4
quality=rare
bonus_power_level=37,base:1
bonus=absorb_max,base:5,item_level:1
```

So we don't need to store everything about an item, the `id` property has both the generated ID as well as the ID of the item we need to inherit from. The nice thing about storing extended items like this is that it should be fairly simple to store other data, such as sockets/durability/identification/etc.

![Image](https://github.com/flareteam/flare-engine/assets/913982/1602ed97-d163-4ff4-809e-01562a1a495f)

**Comment by dorkster** [comment]
Implemented with https://github.com/flareteam/flare-engine/commit/7bb3ffb0cf179b4c8cf6c5954126b79c671ee43f
