### ISSUE TITLE
Item Scaling

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1816]
I kind of got a bit ahead of myself in #1815 when thinking about bonuses per item level for randomly generated items. In actuality, our first order of business should be to handle these scaled properties for the base items. The following properties should be able to have a per-level scaling:

- [x] `requires_level`
- [x] `requires_stat`
- [x] `bonus`
- [x] `bonus_power_level`
- [x] `price`
- [x] `price_sell`

One thing worth noting is that we can scale `price` with `price_per_level`, but it scales with the **player** level. We also want to support other scaling methods such as by **item** level and by primary stats. So I propose extending the syntax of each of these attributes to include the scaled values alongside the base value:

```
bonus=<STAT>,base:<int>,item_level:<int>,player_level:<int>,<PRIMARY_STAT>:<int>

The "base:" prefix would be optional to maintain compatibility. Basically, no prefix = base value.
```

This syntax should even work in #1815, since defining min/max ranges can be done by simply adding another colon, like so:
```
bonus=<STAT>,base:<min>:<max>
```

**Comment by WithinAmnesia** [comment]
Could this be incredibly useful for scaling enemy stats behind the scenes; like scaling monster stats like 'summoned skeleton'? Or is there already something like this?

Either way this could potentially help a lot of people for random encounters like in Oblivion https://levelskip.com/rpgs/wellappointedbandit (or in other cases like modern WoW's item scaling: https://www.wowhead.com/item=60937/restored-archeus ).

I don't like item scaling myself (WoW heirlooms / world scaling to the player not the player scaling to the world I thought was cool at first and then it well kind of felt more like a theme park and less like an adventure. Items that scale to the user's 'power level' don't seem to happen in the real world enough. Yet I think there could be cases where item scaling could help. Like even scaling monsters with undroppable loot to help the devs work go farther perhaps. I think having the option is a good though for it could help in the future and maybe even a critical like myself could find a reasonable way to use this feature and still have an immersive item experience (hopefully XD).
