### ISSUE TITLE
Clearer tip in title screen when no core mod set

### ISSUE THREAD

**Issue by kr4ft3r** [flareteam/flare-engine#1828]
I am new to Flare, and when I ran the game I was greeted with the "Enable a core mod to continue" tooltip on the disabled Play button. So I spent about 40 minutes checking my post-build linking steps, inspecting the console and files, and relaunching the game with different params when all I had to do was go to Configuration/Mods and enable the core mod in-game.

The tip could be made more descriptive for new players. I did not expect the Configuration screen has anything to do with selecting core mods. To avoid messing with all the translation files, something like this could do:

`button_play->tooltip = msg->get("Enable a core mod to continue") + " (" + msg->get("Configuration") + "/" + msg->get("Mods") + ")" `

![flare-title-tooltip](https://user-images.githubusercontent.com/6455225/194664494-4dad3efa-b826-49c9-b33e-04271f909053.png)

**Comment by dorkster** [comment]
I think we can do even better with this:

- Instead of disabling the Play Game button when there is no "core" mod, it should open a dialog with a button to go directly to the Mods configuration page.
- We need to better communicate to players what a core mod in this context actually is. A core mod is any mod that has `enable_playgame=true` in the file `engine/gameplay.txt`. We should indicate if a mod has this flag set in its description tooltip on the configuration page.
- The term "core" is itself a poor choice here, as players will probably assume the *fantasycore* mod would meet the criteria (it doesn't!). Maybe referring to them as "gameplay" mods would be better.

**Comment by kr4ft3r** [comment]
Coincidently, adding the dialogue that takes you to Mods was exactly what I was thinking as well, but I didn't expect you'd be as interested in this change. The first thing that came to my mind was "... You will now be taken to the mod selection screen" leaving no other choice, but maybe that would be too authoritative.

I'm interested in having a poke at this for fun unless you feel like doing it. I didn't even yet get to look at the code enough to have an idea of how dialogues are done, but I imagine it can't be too hard (from what I've seen the code looks pretty neat).

**Comment by dorkster** [comment]
You're welcome to take a stab at it yourself. Dialog boxes are done with the [MenuConfirm](https://github.com/flareteam/flare-engine/blob/master/src/MenuConfirm.cpp) class. An example usage would be the confirmation for deleting save files in [GameStateLoad](https://github.com/flareteam/flare-engine/blob/master/src/GameStateLoad.cpp#L91-L95).

**Comment by kr4ft3r** [comment]
OK I've ended up with two version to choose from. I like the second one better (contextual button).

I'm not finished though as I still have to find out if there is a way to auto-select specific tab (Mods) on configuration screen without altering the code much.

1) Dialogue version: most unpolished, one hurdle here is the dialogue window's only option has redundant left/right arrows around it, haven't yet gotten to look into this.

[https://github.com/kr4ft3r/flare-engine/tree/nomod-dialogue](url)

2) Contextual button version: most simple and user-friendly, the Play button is relabeled as Select Mods button while keeping the "Select core mod to continue" tooltip.

https://github.com/kr4ft3r/flare-engine/tree/nomod-button

![flare-title-button](https://user-images.githubusercontent.com/6455225/194711901-1b06064e-dd86-40da-bdf8-f3a4b2dea24d.png)

**Comment by dorkster** [comment]
I think I still prefer the less subtle approach of the dialog box. To address the issue with the left/right arrows, we just about always include a "Cancel" action (works better for gamepad players). I'd recommend adding it. All it needs to do is close the dialog box without performing any other action.

Also as a personal preference, I'd change the dialog box button text from "Mods" to "Edit Mods" and drop the tooltip text on said button.

As for selecting the correct tab on the config menu, I'd start with the usage code and work my way inwards. In other words, you'd want the code in GameStateTitle to look something like this:

```
GameStateConfig* config = new GameStateConfig;
config->setActiveTab(MenuConfig::MODS_TAB);
setRequestedGameState(config);
```

**Comment by kr4ft3r** [comment]
There is a PR now, shaped to your preferences as you are the lead dev and this is a fairly visible UI change.

Imho, "Edit Mods" button label should be replaced with "Select Mods" or "Enable Mods" (most context accurate), as the purpose is not to edit the mods themselves.

I liked context button over dialogue better as it is more streamlined, and next to everyone who would get to see that state already knows that Flare Engine is meant to run a core module. Also, it doesn't make much sense for Flare Engine without a core module enabled to have a "play" button, as in such state the program is more like a boot loader for core modules.

**Comment by dorkster** [comment]
>Imho, "Edit Mods" button label should be replaced with "Select Mods" or "Enable Mods" (most context accurate), as the purpose is not to edit the mods themselves.

Good point. Honestly, I'll probably just change it back to "Mods" (which is already localized) like you originally had it.

>Also, it doesn't make much sense for Flare Engine without a core module enabled to have a "play" button, as in such state the program is more like a boot loader for core modules.

My thought is that a new player is going to be looking to start playing the game above all else. So having no button with "Play"/"Start"/etc could be a little confusing. By keeping the Play Game button, we don't hide the desired path (only interrupt it).
