### ISSUE TITLE
256x256 size animated spells don't hit enemies but smaller sized ones do?

### ISSUE THREAD

**Issue by WithinAmnesia** [flareteam/flare-engine#1837]
@dorkster These two spells should both work but only the one with the default small fireball animation works.
All this different is the animation:
[furorebolt+.txt](https://github.com/flareteam/flare-engine/files/10253047/furorebolt%2B.txt) This one shoots but does not hit enemies.
[furorebolt-.txt](https://github.com/flareteam/flare-engine/files/10253048/furorebolt-.txt) This one shoots and does hit enemies.
I changed the name to 'furorebolt.txt' to test them back and forth. Just to test one just take the - or + off the end.

Powers
"# Furorebolt #
[power]
id=2
INCLUDE powers/AGABAL/wizard/spells/furorebolt.txt
requires_resource_stat=mana,1
modifier_damage=multiply,100,0"

256x256 X4K Animations work visually but I'm stumped on how they don't work mechanically and do not hit a 512x512 size enemy.
![AGABAL_Furoreball_256x256_X4K+++](https://user-images.githubusercontent.com/86871191/208278296-42745139-647b-423b-8efc-41548196279e.png)
[AGABAL_Furoreball_256x256_X4K+++.txt](https://github.com/flareteam/flare-engine/files/10253079/AGABAL_Furoreball_256x256_X4K%2B%2B%2B.txt)

Default Flare Animations work both visually and mechanically.
![fireball](https://user-images.githubusercontent.com/86871191/208278345-656685ed-349b-431f-93fd-c9f2546eb540.png)
[fireball.txt](https://github.com/flareteam/flare-engine/files/10253081/fireball.txt)

Any possible suggestions?

Is it memory or like something else? I'm not sure what it could be. I am kind of like tuckered out today after like battling to get the 4K spell graphics rendered and animation visually working. So I could be missing a simple error so yeah who knows?

**Comment by dorkster** [comment]
The `active_frame` property is missing from the 4x animation file. This defines one or more frames in which the animation is considered "active". For powers, "active" means when it can hit the target. In the case of the fireball, all the frames should be active. So use `active_frame=all` as seen [here](https://github.com/flareteam/flare-game/blob/master/mods/fantasycore/animations/powers/fireball.txt#L8).

**Comment by WithinAmnesia** [comment]
Ahhhhh thank you.
