### ISSUE TITLE
Fastlane metadata for F-Droid

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1843]
As talked about [here](https://github.com/flareteam/flare-engine/issues/1387#issuecomment-1368341627), we're looking to get the Android port of Flare into the F-Droid repos. F-Droid recommends using the [Fastlane](https://gitlab.com/-/snippets/1895688) structure for metadata, such as descriptions and screenshots.

Since the Android port is distributed as engine-only for now, this metadata should be in this repo as opposed to flare-game.

**Comment by Korb** [comment]
Screenshots are still not showing up on [this game' page in F-Droid](https://f-droid.org/packages/org.flare.app/):

![Screenshot_2023_0414_222950_org fdroid fdroid](https://user-images.githubusercontent.com/3509797/232138510-2a9abe00-eb1a-4bae-9274-ed7ca1b4926a.jpg)

**Comment by Korb** [comment]
There are still no screenshots to better understand what the application is like.
