### ISSUE TITLE
Critical data deletion

### ISSUE THREAD

**Issue by MannajaX** [flareteam/flare-engine#1851]
I was messing with a passive that has consume_corpse and calls a script on_cast (to do a kill spree combo).
The script calls a power that applies a buff to the hero.
Well, on changing maps, my game crashes and my save gets deleted (character starts fresh and hasn't even basic items).
Game time is reset to 0.
This is not an issue for me as it was just a test character.
Hopefully this can be found and fixed, or maybe I can be shown what I'm doing wrong with this setup.

**Comment by dorkster** [comment]
Can you provide the power definition(s) and the script?

**Comment by MannajaX** [comment]
#on-kill speed boost
[power]
id=2035
type=fixed
passive=true
requires_corpse=consume
script=on_cast,scripts/powers/frenzy.txt

The script casts the following power. Script casted powers seem to always be cast at the hero, as if an enemy was
targeting them. 

[power]
id=2036
type=fixed
source_type=enemy
use_hazard=true
radius=2
multitarget=true
ignore_zero_damage=true
post_effect=champion_runes,1,10s
post_effect=haste,130,10s

This is my current way of doing on-kill :)   Hacky I know
This won't crash a game immediately, but from testing it will eventually crash and delete the data.

**Comment by dorkster** [comment]
No luck getting a crash after ~20 minutes of play. I *did* comment out the "champion_runes" post effect, but I doubt that has any impact. I'm actually a little surprised that `requires_corpse` "works" with passive powers, but I guess it makes sense where `requires_corpse` uses the last targeted enemy. However, I don't immediately see it as the cause of your crashing.

You're welcome to email me (jajdorkster@gmail.com) a copy of your mod for further testing.
