### ISSUE TITLE
Behavior of power.target_neighbor

### ISSUE THREAD

**Issue by MannajaX** [flareteam/flare-engine#1853]
power.target_neighbor is a very useful functionality.
It will target tiles near your character always however.
Would be better if it was a radius around the target (create multiple hazards at a target location.)
It will also choose tiles in collision locations (pits/walls). Even if power.requires_los and power.requires_empty_target are on.

This can also be useful when summoning a unit. Right now failing to summon on target (because tile is occupied), will summon near you instead.
The desired behaviour is to summon near the target tile (in case of a decoy, you don't want to summon it near you).

**Comment by dorkster** [comment]
Partially fixed in b0f9eafbad9adcddb1baab87572edbee39107c53. Still need to address targeting of pits/walls.
