### ISSUE TITLE
Random Map Selector

### ISSUE THREAD

**Issue by CaptainFluffy1903** [flareteam/flare-engine#1859]
I know the next uptade will add a random item generation feature, what about maps?I know its too hard to make a random map(dungeon) generator but, what about a selector?There will be already done maps and it will randomly choose it.

**Comment by dorkster** [comment]
This can be done using the `intermap_random` event attribute. It's how we select a random map for the Halls of Infinity:

https://github.com/flareteam/flare-game/blob/master/mods/empyrean_campaign/npcs/base/infinity_obelisk.txt#L13
https://github.com/flareteam/flare-game/blob/master/mods/empyrean_campaign/maps/halls_of_infinity/maplist.txt
