### ISSUE TITLE
Adding hotspot to mapmod property to make loot events easier to make.

### ISSUE THREAD

**Issue by CaptainFluffy1903** [flareteam/flare-engine#1861]
U have to enter the cordinates and its a bit tiring to make.If we can use hotspot at mapmod all we have to do will become copy event and drag it to the new loot.Idk is it possible to make but if its possible that would be easier to make mods for modders.

**Comment by dorkster** [comment]
Good news: The Tiled extension in the [flare-tiled-tools](https://github.com/flareteam/flare-tiled-tools#using-the-mapmod-feature) repo has tools for this. It lets you paint on temporary layers that can then be converted into a mapmod event.

Here's a clip showing it in action:

https://github.com/flareteam/flare-engine/assets/913982/1a3b0318-1fd6-4fd3-905a-756c232abe2d
