### ISSUE TITLE
Open Source commercial friendly CC0 / MIT / 'Public Domain' license Flare Engine port version for Godot 4+?

### ISSUE THREAD

**Issue by WithinAmnesia** [flareteam/flare-engine#1862]
https://itch.io/c/1557879/lucifer
There is no ~complete Diablo style engine 'template' for Godot 4+. This is an unsolved issue for trying to build or port over RPG work / games and projects from various game engines into a 2D game version on Godot 4+ from various powerful well loved game engines and game genres. Such as like with Baldur's Gate, World of Warcraft, Flare, Unity, RPG Maker, Unreal and a lot of work with design and themes found with printed / text / pen and paper media like books, illustrations, stories, concepts and many game design systems. Overwhelmingly all of these beloved 'ARPG game engines' run on game engines like Diablo / Zelda / ~'Grand RPGs' like WoW and or Baldur's Gate. What should one do to get an Open Source commercial friendly CC0 / MIT / 'Public Domain' license Flare Engine port version for empowering the world and RPG community to be able to create forever free video games inspired from from ~Diablo / Zelda / ~'Grand RPGs' on Godot 4+?

There are various tutorials on how to create elements of this ~'Grand RPG' like Diablo / Zelda yet they are incomplete currently:
https://www.youtube.com/watch?v=pBoXqW4RykE&list=PL3cGrGHvkwn0zoGLoGorwvGj6dHCjLaGd&ab_channel=DevWorm
https://www.youtube.com/watch?v=bS-tX2HopW0&ab_channel=GDQuest
https://www.youtube.com/watch?v=oq_s5Ivg4Ow&ab_channel=GameDevelopmentCenter
https://www.youtube.com/watch?v=0mUoRdYe0s4&list=PLMQtM2GgbPEVuTgD4Ln17ombTg6EahSLr&ab_channel=MakerTech
https://www.youtube.com/watch?v=AkKywZDJNeE&ab_channel=Arkeve
https://www.youtube.com/watch?v=Vi0V1D5A7qI&ab_channel=FoozleCC
https://www.youtube.com/playlist?list=PL9FzW-m48fn2SlrW0KoLT4n5egNdX-W9a

Godot 4+ seems to be a great place to bridge the gap from the digital wilderness and to main public appreciation of hard and beautiful independent developer work. Godot 4+ seems to be tailor designed for individuals and small scale operations and there are no profit cuts or very restrictive licenses and has the power to be distributed to nearly every platform PC, Mobile and Consoles; Godot 4+ intrinsically pairs incredibly well with itch.io. Of which itch.io has the same community friendly free and pay-what-you-want ~0% profit cut with ~100% profit going to the developer and better supporting individual creative developers and artists of the world creative community with great welcoming community support and positive future thinking nature where freedom is everything. If only there was a way to have the best of all the creative community worlds united.
https://godotengine.org/

**Comment by WithinAmnesia** [comment]
@dorkster I feel this should be a discussion of sorts for I have a lot of ideas that haunt myself this this subject.

**Comment by WithinAmnesia** [comment]
Flare cannot do multiplayer this I feel has troubled many people including myself.
Godot has a big staff and is free and open source with a very friendly MIT license that is proven to work for commercial projects as well across nearly all platforms PC, Mobile and Consoles.
Godot 4+ has successfully implemented seriously impressive multiplayer functionality: https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html

I am also troubled by the Solaris Engine: https://www.solarus-games.org/features/ . It has a limited future yet has an incredible linage and a beautiful vision for the future. Yet it has very limited prospects going forward and is free and open source as well. Perhaps we can save them too for a Diablo / Zelda hybrid like a ~'Ziablo'?

I am troubled by the gaming industry it feels more and more that it is up to the community now to make high quality RPGs and 2D games are the foundations of most all majorly successful video game series. https://en.wikipedia.org/wiki/List_of_best-selling_video_game_franchises most of the top 50 best selling video game franchise started in the 2D era from the 1970's to 2000's and a lot from the 80's and 90's specifically. As I have pushed the Unreal engine to its limited and beyond and with great help we did 4K Flare engine it seems I still cannot be immune to raw efficiency of development of 2D games. Its very hard to beat a 2D game for a start as a single person or a small team which is the vast majority of people who wish to start making video games.

I was banned from Classic World of Warcraft Wrath of Lich King for talking in world chat, I practically grew up in WoW and was raised by the online community, I never had much of family but I always had video games and in my decades of adventure I have been banned for talking in world chat. I was not banned by a human, but a robot. This video sums it up very clearly and is very funny still. https://www.youtube.com/watch?v=X2syg93jfvk&ab_channel=CaptainGrim

I have done my best to rally the Private server community for WoW to bring back new thrilling 40 person raiding. Yet it is not enough, WoW is old and dying. World of Warcraft came from the Warcraft RTS series which came from the days of 16 bit gaming on the SNES and Blizzard started work on their first game a modified 8 bit game from the NES. Warcraft started as a RTS modified version of The Lost Vikings: https://old.reddit.com/r/wow/comments/bokx62/warcraft_started_as_the_lost_vikings_rts/ . With Diablo 4 in the dumps https://www.metacritic.com/game/pc/diablo-iv/user-reviews and Final Fantasy XIV not being a worthy successor it seems that the burden is now on the community to create grand RPGs.

I tried my best for Flare, we pushed it to 4K https://github.com/flareteam/flare-game/discussions/940 but it does not support multiplayer and to make those 4K graphics was a nightmare to be honest for it was incredibly complex to add more and more and more. I explored Unreal engine and rallied the best RPG creatives in the world together for one cause to make the foundation of a grand RPG that is multiplayer and in 8K with the most advanced controls and graphics in the world. Yet it is a hard slow slog grinding on for years but there are thrilling successes. https://www.youtube.com/watch?v=18zEhXInJag&ab_channel=CTGame + https://www.youtube.com/watch?v=994FgtShOi4&ab_channel=EasySystems + https://www.youtube.com/watch?v=4Rjspwrw5oo&ab_channel=CTGame Yet this is only for the most hardened more intense and ferocious of game developers in the world. Literally thousands have tried yet less than 10 have succeeded in the unreal community to bring about these epic successes for the world's RPG developer community.

Thus I turned to where it all began and as I search and downloaded every free CC0 asset on itch.io and opengameart.org to better learn and feel what is 2D game art and to save as much as I could I came to learn that 2D games are what most people need to start. They are easiest to start and tinker with and they offer a sound solid foundation for more advanced adventures later on. Itch.io is the home of new independent game developers just trying to begin and its like first friendly stop off from the digital wasteland wildness which I grew up within honing the skills and being ever sharper as the years and decades march onwards.

We are at a crossroads in time it feels the end of the monolithic corporate past and the beginning of new forever free future. I am trying to find ways for regular everyday people to have a chance to make the game of their dreams yet it is still to hard to start and many people give up before they even truly began and it haunts me greatly wandering this graveyard of dreams.

All the RPGs seem to play the same, the all come from the same games, and mythology; Fairy-tales pre-1800's-1900's, Tolkien 1930-1950's, D&D 1970's, PC and Arcade and Consoles 1970's-1980's, Zelda 1986, Diablo 1997, WoW 2004. Yet the creative community lacks a forever free ~'Grand RPG' engine that welcomes all the creative dreamers of the world.

How many dreams have died already because people simply did not have a chance to even start making a game? Not everyone can code and is an artist and talented in multiple disciplines, not many people have any friends who can help. I have searched far and wide across the world online just to find a handful of creative ferociously talented people who have a common heart who care about the future of this gaming community. Even this I am not sure it is enough yet I still hope.

I look at these assets, made from an anonymous source ~'Baldur Something' that commissioned one the world's greatest 2D artists for the whole world to be better with as CC0 ~public domain assets and yet these master pieces have no engine, it has no heart beat. https://itch.io/c/1557879/lucifer + https://foozlecc.itch.io/lucifer-exterior-tileset + https://foozlecc.itch.io/lucifer-warrior

I ask who can give these assets a worthy heart beat? The Lucifer 2D art set is meant to be an CC0 / MIT / ~'Public Domain' Diablo / Zelda / ~'Grand RPG' engine for the whole world to benefit from and right now more than ever the world needs a chance. Who can give the world a chance? I found this person from Ukraine who works with Godot making Diablo and Zelda and ~'Grand RPG' like elements https://github.com/don-tnowe and I wonder who else can help the world and save all these dreams of great RPGs? How long do we really have left to do something that makes the world a better place? Who will rise to make ~'Grand RPGs' forever free?

**Comment by WithinAmnesia** [comment]
I created an open source GitHub repository for making an Open Source MIT license Action Role Playing Game  template for Godot Engine 4+. https://github.com/WithinAmnesia/ARPG . It's a start. I think if its made open and community driven it can empower m any people across the world. Yet it still early days and humble beginnings.

**Comment by dorkster** [comment]
I've never used Godot, everything I hear sounds really good. If someone was serious about making a port/clone of Flare in Godot, I would be happy to advise them. I'm not interested in leading such an endeavor myself.

>I created an open source GitHub repository for making an Open Source MIT license Action Role Playing Game template for Godot Engine 4+. https://github.com/WithinAmnesia/ARPG

I see you've started collecting some assets, but what are your plans for starting development of the source code?
- Basing it on one of the tutorials you linked (looks like GDQuest is open source)?
- Writing it yourself?
- No plan, and just hoping that someone else comes along to do it?

That last one might sound harsh. But if that's the honest answer, I can't see the project gaining any traction or attracting contributors. "Build it and they will come" implies that something is built first.

**Comment by WithinAmnesia** [comment]
> I've never used Godot, everything I hear sounds really good. If someone was serious about making a port/clone of Flare in Godot, I would be happy to advise them. I'm not interested in leading such an endeavor myself.
> 
> > I created an open source GitHub repository for making an Open Source MIT license Action Role Playing Game template for Godot Engine 4+. https://github.com/WithinAmnesia/ARPG
> 
> I see you've started collecting some assets, but what are your plans for starting development of the source code?
> 
>     * Basing it on one of the tutorials you linked (looks like GDQuest is open source)?
> 
>     * Writing it yourself?
> 
>     * No plan, and just hoping that someone else comes along to do it?
> 
> 
> That last one might sound harsh. But if that's the honest answer, I can't see the project gaining any traction or attracting contributors. "Build it and they will come" implies that something is built first.

The source code or script / a working example I am currently building. I have a working prototype but I am rebuilding it so that it only uses open source C.C.0 / M.I.T. / ~'template' assets. I understand the need for a basic demonstration gamer and I am working to create an example like what https://github.com/don-tnowe/ has created with download 'plug and play' demonstration games that work with Godot: https://github.com/don-tnowe/godot-wyvernshield-triggers/tree/main + https://github.com/don-tnowe/godot-wyvernbox-inventory .

I tried to convert my working prototype but I just scrapped that idea and am I rebuilding it fresh. I am following these tutorials more or less as very basic start just to get a simple start for people to test and tinker with using the Lucifer C.C.0 2D game assets https://www.youtube.com/playlist?list=PL3cGrGHvkwn0zoGLoGorwvGj6dHCjLaGd .

The core demonstration game template I hope will be very simple at the start. As in the 'alpha' will mostly be a compilation of all these ARPG Godot tutorials online blended together in a convenient spot using C.C.0 Lucifer 2D assets for anyone to tinker with. It is very much inspired from Flare where it is built from open source assets with open source code / scripts making everything run within player expectations for a proper ARPG. This case with Godot Engine 4+ is basically like Flare but 2D and using open source / C.C.0 / M.I.T. game assets and just like Flare is built open source for everyone by everyone. I am just a single person trying to put these wonderful open source assets to good use for everyone to benefit from. I imagine if I do my job properly it can help the community and as long as there is good starting demonstration game it should grow bit by bit; just like Flare.

**Comment by WithinAmnesia** [comment]
I am not as good a scripter / coder as you @dorkster so the Flare port for Godot is going to start as the best I can do with very elementary rudimentary ARPG basics fundamentals to start with. I am aiming to make combat at least functional to start like it might feel very simple like what the best tutorials online can offer and it might end up a lot like 2D Zelda to start with and I hope to expand it from there.

I am hoping to have something similar to what https://github.com/don-tnowe/ has with open source ~'Grand RPG' elements working in Godot 4+ such as an inventory system very similar to Flare's inventory and like here is a web demo of that: https://redbladegames.netlify.app/randomlooter/index.html As in this is very similar to Flare and Also Don has another 'Wyvern Series' ~'Grand RPG' mechanics systems thing template for Godot 4+ https://github.com/don-tnowe/godot-wyvernshield-triggers which is like a statistics system https://github.com/don-tnowe/godot-wyvernshield-triggers/issues/1#issuecomment-1646960436 .

So there are some base core primordial fundamental elements of ~'Grand ARPGs' floating around open source for Godot 4+ already its just they are not combined / complied in one place yet but very well could be with a good open source starting demonstration template game like the one I am working on. The Flare port to Godot 4+ will most likely start as a very elementary rough approximation of Flare working on Godot 4+ to start but hopefully eventually over time it can grow the way Flare did and bit by bit it can start to grow into a proper ~'Grand RPG' that fits better with people's expectations of what should an open source Godot 4+ 2D ARPG.

**Comment by dorkster** [comment]
Closing this now that a forum thread, https://github.com/flareteam/flare-game/discussions/946, is up.
