### ISSUE TITLE
Have some trouble with a map.

### ISSUE THREAD

**Issue by CaptainFluffy1903** [flareteam/flare-engine#1865]
<img width="481" alt="Ekran görüntüsü 2023-07-30 193650" src="https://github.com/flareteam/flare-engine/assets/122923399/4a7ca225-9ca3-408f-84b5-5885e07880c9">
<img width="476" alt="Ekran görüntüsü 2023-07-30 193628" src="https://github.com/flareteam/flare-engine/assets/122923399/07996255-679d-4415-9770-fa47016bafe0">
[https://opengameart.org/content/room-tileset]
This is the link of tileset, ı generated the tileset definition with tiled tools, even with old tileset def generator tool.
What I did wrong?I didnt encounter a problem like this with the other maps I made with new tilesets.

**Comment by dorkster** [comment]
Hmm looks fine for me after using the Tiled tools package:
![Screenshot_20230730_142027](https://github.com/flareteam/flare-engine/assets/913982/2f131146-ea79-4cc7-9a76-ebc210193e69)

The tile size for the tileset should be 64x128.

Here's a copy of my [tileset definition](https://github.com/flareteam/flare-engine/files/12209828/room.txt).

**Comment by dorkster** [comment]
Here you go, this includes a blank Tiled template as well as an example map: [room_example.zip](https://github.com/flareteam/flare-engine/files/12217340/room_example.zip)

**Comment by CaptainFluffy1903** [comment]
I dont know why that happened but thanks, now it works well.

**Comment by dorkster** [comment]
> Maybe its because of I didnt added rules tileset.Can this make tile ids incorrect?

The Tiled script is made to handle the presence (or absence) of the "collision" and "set_rules" tilesets. But those tileset names are literal. So if your collision tileset was named something else, e.g. "tiled_collision", that could have introduced an unintended offset.
