### ISSUE TITLE
How to generate translation files?

### ISSUE THREAD

**Issue by CaptainFluffy1903** [flareteam/flare-engine#1866]
How do we generate our own .po translation files?Am ı have to found and write every msg id there?Is there a tool or something else?(Probably there is one)

**Comment by dorkster** [comment]
There is a set of scripts included in the engine's default mod for .pot/.po generation:

- [regenerate_po.sh](https://github.com/flareteam/flare-engine/blob/master/mods/default/languages/regenerate_po.sh)
- [xgettext.py (required by regenerate_po.sh)](https://github.com/flareteam/flare-engine/blob/master/mods/default/languages/xgettext.py)

1. Place these scripts in your mod's `languages` folder
2. Create an empty `data.pot` file
3. Run `./regenerate_po.sh`, which will update the `data.pot` file with all the strings found in your mod. If you have existing translations that you want to update with new msgids, use `./regenerate_po.sh --do-merge`
