### ISSUE TITLE
Android Flare Engine v1.14 APK showing as version 1.12

### ISSUE THREAD

**Issue by BRBsoup** [flareteam/flare-engine#1874]
In-game is shown properly, but the APK install package/android manifest info shows as "1.12"/"112"

**Comment by BRBsoup** [comment]
I think the APK being distributed was just built with the old manifest, as in the source code the manifest correctly shows 1.14/114

**Comment by dorkster** [comment]
I believe this is just the F-Droid manifest containing the wrong version number. I'll look into getting this fixed.

Also, no need to double-post on both flare-engine and flare-game.

**Comment by BRBsoup** [comment]
> I believe this is just the F-Droid manifest containing the wrong version number. I'll look into getting this fixed.
> 
> Also, no need to double-post on both flare-engine and flare-game.

Sorry for double post, I wasn't sure because the APK is distributed under flare-game. It's happening on the APK distributed here, so not sure about F-Droid. In fact, I saw that F-Droid version was 1.12 and older. So I went directly to the website.

![Screenshot_20231104_233517_Material Files](https://github.com/flareteam/flare-engine/assets/120071873/65d7b872-32da-410f-90ff-fbfb3c37ff32)

**Comment by dorkster** [comment]
Wait, I think you're right. I just built it and the APK version still says 1.12. Not sure where it's getting that number from, since AndroidManifest.xml has 1.14. The F-Droid manifest still needs to be corrected, but it needs to be fixed on our end first.

**Comment by BRBsoup** [comment]
> Wait, I think you're right. I just built it and the APK version still says 1.12. Not sure where it's getting that number from, since AndroidManifest.xml has 1.14. The F-Droid manifest still needs to be corrected, but it needs to be fixed on our end first.

I attached a few screenshots which shows my APK installer showing the manifest as 112 yet on git its 114. Yeah, it's odd. Good luck figuring it out, versioning is pretty important for Android apps, though at least it doesn't seem to affect any of the actual engine/game. Also, thank you!

**Comment by dorkster** [comment]
I completely forgot that I [fixed this](https://github.com/flareteam/flare-engine/commit/45f259aafa3bb74236e7627952bfe0227f838fd6), but it was after the v1.14 tag. So my v1.14 builds didn't have it.

I made the `v1.14-android` tag with the fix cherry-picked. I'll rebuild our APKs with it, as well as submit a fixed manifest to F-Droid (once CI finishes).
