### ISSUE TITLE
number_format.txt missing

### ISSUE THREAD

**Issue by doggodanubus** [flareteam/flare-engine#1877]
The engine complains of this. It appears it should be added in release notes but I'm unable to find it.

**Comment by dorkster** [comment]
From the 1.14 release notes:

>Added engine/number_format.txt. This file defines the number of digits to print after the decimal point for fractional values under different contexts.

More details in the attribute reference: https://github.com/flareteam/flare-engine/wiki/Attribute-Reference#enginesettings-number-format

This file is actually optional, so it's not supposed to have an error message when missing. I'll fix that.
