### ISSUE TITLE
NPCs in town are not clickable on new source code

### ISSUE THREAD

**Issue by revevil** [flareteam/flare-engine#1890]
Hello, I would like to report that I have git cloned flare-engine and flare-game from the latest source code. It is build 1.14.76. I am running the Empyrean Campaign. Just to let you know, the NPCs in town are not clickable. I'm not sure why or even if this is a bug. I did notice character movement has improved. I did try using an old save, then moved the saved folder and created a new save (just to make sure that is wasn't the old save) but same effect. When the mouse hovers over the NPC, there is no name or title, and they are not clickable. To be clear, I am running the latest version of Linux Mint with MATE desktop. I was just curious if anyone else is running into this issue.

**Comment by dorkster** [comment]
Sorry, that was a silly regression on my part. It should be fixed now in 1.14.77.

**Comment by revevil** [comment]
> Sorry, that was a silly regression on my part. It should be fixed now in 1.14.77.

Ok thank you!
